@echo off
setlocal EnableDelayedExpansion
REM ============================================================================
REM  build_ff.bat  -  rebuilds mod.ff with OpenAssetTools' Linker.
REM ----------------------------------------------------------------------------
REM  This is SEPARATE from build.bat and is only needed when you change something
REM  under zone_source\ or zone_assets\ (materials, images, and anything else that
REM  has to live inside a fastfile). Editing .gsc does NOT need this - raw script
REM  goes into mod.iwd via build.bat and never touches mod.ff.
REM
REM  HOW IT WORKS
REM    zone_source\base\mod.ff    the pristine fastfile this project shipped with.
REM                               It is the DONOR for the 3,510 assets already in
REM                               mod.ff (perk bottles, camos, weapons, xanims,
REM                               the baked scripts...). We have no source for
REM                               those, so the Linker copies them straight out of
REM                               this file. DO NOT DELETE IT - it is unrecoverable.
REM
REM  *** It must stay named exactly mod.ff, in its own folder. ***
REM  A T6 fastfile's internal zone name is part of how its compressed streams are
REM  read back; rename the file and OAT fails with "inflate of stream N failed:
REM  invalid block type". Same bytes, different filename = unloadable. That is why
REM  the donor lives in a subfolder instead of being called mod_base.ff.
REM    zone_source\mod_base.zone  that file's asset inventory, generated by the
REM                               Unlinker. Regenerate with:  build_ff.bat regen
REM    zone_source\mod_locations.zone  the assets this project adds.
REM    zone_assets\               material .json + image .iwi sources for them.
REM
REM  Always links from the donor, never from the current mod.ff, so repeated
REM  runs are deterministic and cannot compound.
REM ============================================================================

set "PROJ=%~dp0"
if "%PROJ:~-1%"=="\" set "PROJ=%PROJ:~0,-1%"

REM --- OpenAssetTools ---------------------------------------------------------
if not defined OAT_BASE set "OAT_BASE=H:\Claude\oat-windows"
if not exist "%OAT_BASE%\Linker.exe" (
    echo   ERROR: Linker.exe not found in "%OAT_BASE%".
    echo          Set OAT_BASE to your OpenAssetTools folder and re-run.
    exit /b 1
)

REM --- Black Ops II install (needed for stock assets referenced by our materials)
if not defined BO2_DIR set "BO2_DIR=F:\SteamLibrary\steamapps\common\Call of Duty Black Ops II"
if not exist "%BO2_DIR%\zone\all\ui_zm.ff" (
    echo   ERROR: ui_zm.ff not found under "%BO2_DIR%\zone\all".
    echo          Set BO2_DIR to your Black Ops II install folder and re-run.
    exit /b 1
)

if not exist "%PROJ%\zone_source\base\mod.ff" (
    echo   ERROR: zone_source\base\mod.ff is missing. It is the only copy of the
    echo          3,510 assets already in mod.ff and cannot be regenerated.
    exit /b 1
)

REM --- regen mode: rebuild mod_base.zone from mod_base.ff ----------------------
if /i "%~1"=="regen" (
    echo   Regenerating zone_source\mod_base.zone from base\mod.ff ...
    "%OAT_BASE%\Unlinker.exe" --include-assets keyvaluepairs -o "%PROJ%\zone_source\_regen" "%PROJ%\zone_source\base\mod.ff"
    if errorlevel 1 ( echo   ERROR: Unlinker failed. & exit /b 1 )
    copy /y "%PROJ%\zone_source\_regen\zone_source\mod.zone" "%PROJ%\zone_source\mod_base.zone" >nul
    rmdir /s /q "%PROJ%\zone_source\_regen"
    echo   mod_base.zone regenerated. Re-run build_ff.bat without 'regen' to link.
    exit /b 0
)

REM --- link -------------------------------------------------------------------
echo   Linking mod.ff ...
if exist "%PROJ%\zone_out" rmdir /s /q "%PROJ%\zone_out"

"%OAT_BASE%\Linker.exe" ^
  --load "%PROJ%\zone_source\base\mod.ff" ^
  --load "%BO2_DIR%\zone\all\ui_zm.ff" ^
  --load "%BO2_DIR%\zone\all\so_zsurvival_zm_transit.ff" ^
  --load "%BO2_DIR%\zone\all\so_zclassic_zm_prison.ff" ^
  --load "%BO2_DIR%\zone\all\zm_tomb.ff" ^
  --base-folder "%PROJ%" ^
  --add-asset-search-path "%PROJ%\zone_assets" ^
  --add-source-search-path "%PROJ%\zone_source" ^
  --output-folder "%PROJ%\zone_out" ^
  mod

if errorlevel 1 (
    echo.
    echo   ERROR: link failed - mod.ff NOT replaced.
    exit /b 1
)

if not exist "%PROJ%\zone_out\mod.ff" (
    echo   ERROR: Linker reported success but produced no mod.ff.
    exit /b 1
)

copy /y "%PROJ%\zone_out\mod.ff" "%PROJ%\mod.ff" >nul
rmdir /s /q "%PROJ%\zone_out"

for %%F in ("%PROJ%\mod.ff") do echo   mod.ff rebuilt: %%~zF bytes
echo   Now run build.bat to repack and deploy.
exit /b 0
