@echo off
setlocal EnableDelayedExpansion
REM ============================================================================
REM  build_ff.bat  -  rebuilds mod.ff with OpenAssetTools' Linker.
REM ----------------------------------------------------------------------------
REM  This is SEPARATE from build.bat and is only needed when you change something
REM  under zone_source\ or zone_assets\ (materials, images, and anything else that
REM  has to live inside a fastfile). Editing .gsc does NOT need this - raw script
REM  goes into mod.iwd via build.bat and never touches mod.ff.
REM
REM  HOW IT WORKS
REM    zone_source\base\mod.ff    the pristine fastfile this project shipped with.
REM                               It is the DONOR for the 3,510 assets already in
REM                               mod.ff (perk bottles, camos, weapons, xanims,
REM                               the baked scripts...). We have no source for
REM                               those, so the Linker copies them straight out of
REM                               this file. DO NOT DELETE IT - it is unrecoverable.
REM
REM  *** It must stay named exactly mod.ff, in its own folder. ***
REM  A T6 fastfile's internal zone name is part of how its compressed streams are
REM  read back; rename the file and OAT fails with "inflate of stream N failed:
REM  invalid block type". Same bytes, different filename = unloadable. That is why
REM  the donor lives in a subfolder instead of being called mod_base.ff.
REM    zone_source\mod_base.zone  that file's asset inventory, generated by the
REM                               Unlinker. Regenerate with:  build_ff.bat regen
REM    zone_source\mod_locations.zone  the assets this project adds.
REM    zone_assets\               material .json + image .iwi sources for them.
REM
REM  Always links from the donor, never from the current mod.ff, so repeated
REM  runs are deterministic and cannot compound.
REM ============================================================================

set "PROJ=%~dp0"
if "%PROJ:~-1%"=="\" set "PROJ=%PROJ:~0,-1%"

REM --- OpenAssetTools ---------------------------------------------------------
if not defined OAT_BASE set "OAT_BASE=H:\Claude\oat-windows"
if not exist "%OAT_BASE%\Linker.exe" (
    echo   ERROR: Linker.exe not found in "%OAT_BASE%".
    echo          Set OAT_BASE to your OpenAssetTools folder and re-run.
    exit /b 1
)

REM --- Black Ops II install (needed for stock assets referenced by our materials)
if not defined BO2_DIR set "BO2_DIR=F:\SteamLibrary\steamapps\common\Call of Duty Black Ops II"
if not exist "%BO2_DIR%\zone\all\ui_zm.ff" (
    echo   ERROR: ui_zm.ff not found under "%BO2_DIR%\zone\all".
    echo          Set BO2_DIR to your Black Ops II install folder and re-run.
    exit /b 1
)

if not exist "%PROJ%\zone_source\base\mod.ff" (
    echo   ERROR: zone_source\base\mod.ff is missing. It is the only copy of the
    echo          3,510 assets already in mod.ff and cannot be regenerated.
    exit /b 1
)

REM --- regen mode: rebuild mod_base.zone from mod_base.ff ----------------------
if /i "%~1"=="regen" (
    echo   Regenerating zone_source\mod_base.zone from base\mod.ff ...
    "%OAT_BASE%\Unlinker.exe" --include-assets keyvaluepairs -o "%PROJ%\zone_source\_regen" "%PROJ%\zone_source\base\mod.ff"
    if errorlevel 1 ( echo   ERROR: Unlinker failed. & exit /b 1 )
    copy /y "%PROJ%\zone_source\_regen\zone_source\mod.zone" "%PROJ%\zone_source\mod_base.zone" >nul
    rmdir /s /q "%PROJ%\zone_source\_regen"
    echo   mod_base.zone regenerated. Re-run build_ff.bat without 'regen' to link.
    exit /b 0
)

REM --- stage current .csc sources so mod.ff does not keep a stale copy ---------
REM  mod_base.zone (the donor's inventory) declares scripts/zm/zm_expanded.csc and
REM  the six per-map .csc files. T6 stores scripts in a fastfile as RAW TEXT, and
REM  the Linker resolves each declared asset from the asset search path FIRST and
REM  only falls back to a --load'ed fastfile. With nothing staged, every relink
REM  copied the donor's original .csc back in - so mod.ff kept shipping whatever
REM  those files looked like the day the mod was first built, no matter how much
REM  the working copies changed.
REM
REM  Unlike .gsc - which Plutonium's Mods menu happily runs raw out of mod.iwd
REM  (that is how ridgelandproject.gsc works, and it is declared in no zone file)
REM  - client scripts are conventionally only loaded from the fastfile. Staging
REM  them here means the copy in mod.ff is always the current source, so it does
REM  not matter which of the two the engine ends up preferring.
echo   Staging current .csc sources into zone_assets ...
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$proj='%PROJ%'; $n=0; Get-ChildItem -LiteralPath (Join-Path $proj 'scripts') -Recurse -Filter *.csc | ForEach-Object { $rel=$_.FullName.Substring($proj.Length+1); $dst=Join-Path (Join-Path $proj 'zone_assets') $rel; $dir=Split-Path $dst -Parent; if(-not (Test-Path -LiteralPath $dir)){ New-Item -ItemType Directory -Path $dir -Force | Out-Null }; Copy-Item -LiteralPath $_.FullName -Destination $dst -Force; Write-Host ('    [stage] ' + $rel); $n++ }; Write-Host ('    ' + $n + ' client script(s) staged')"
if errorlevel 1 ( echo   ERROR: could not stage .csc sources. & exit /b 1 )

REM --- stage the sound bank source --------------------------------------------
REM  A T6 sound alias is built from a 60-column CSV plus the WAV/FLAC it names in
REM  its FileSource column. To add ONE alias the Linker still has to rebuild the
REM  WHOLE bank, so it needs the full table and every payload the donor already
REM  had - 1,691 aliases over 249 distinct audio files.
REM
REM  Both come straight back out of the donor, so none of it is checked in:
REM      Unlinker --include-assets soundbank --search-path <base>  ->  the CSV
REM                                                                    AND the audio
REM  🛑 --search-path must point at zone_source\base, never at the project root.
REM  The root mod.all.sabl is a BUILD OUTPUT once this script has run; dumping from
REM  it would feed each build its own previous output and compound. Same rule as
REM  linking from base\mod.ff instead of the live mod.ff.
REM
REM  🛑 Dump the CSV and the payloads in the SAME Unlinker run. It writes files named
REM  foo.snd.wav.wav - its own extension on top of the FileSource name - and rewrites
REM  the CSV's FileSource column to match, so the two agree only if they come from one
REM  run. Taking the CSV from a payload-less dump (FileSource "foo.snd.wav") and the
REM  audio from a dump with --search-path ("foo.snd.wav.wav"), in either direction,
REM  fails with "Unable to find a compatible file for sound ...". Do not "fix" the
REM  doubled extension - the CSV expects it.
if not exist "%PROJ%\zone_assets\soundbank\mod.all.aliases.csv" (
    echo   Extracting the donor sound bank ^(first run only, ~250 files^) ...
    if exist "%PROJ%\zone_assets\_snd_dump" rmdir /s /q "%PROJ%\zone_assets\_snd_dump"
    "%OAT_BASE%\Unlinker.exe" --include-assets soundbank --search-path "%PROJ%\zone_source\base" -o "%PROJ%\zone_assets\_snd_dump" "%PROJ%\zone_source\base\mod.ff" >nul
    if errorlevel 1 ( echo   ERROR: could not extract the donor sound bank. & exit /b 1 )
    "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$p='%PROJ%'; $d=Join-Path $p 'zone_assets\_snd_dump'; New-Item -ItemType Directory -Force -Path (Join-Path $p 'zone_assets\soundbank') | Out-Null; Copy-Item (Join-Path $d 'soundbank\mod.all.aliases.csv') (Join-Path $p 'zone_assets\soundbank\mod.all.aliases.csv') -Force; $n=0; Get-ChildItem -LiteralPath (Join-Path $d 'sound') -Recurse -File | ForEach-Object { $rel=$_.FullName.Substring((Join-Path $d '').Length); $dst=Join-Path (Join-Path $p 'zone_assets') $rel; $dir=Split-Path $dst -Parent; if(-not (Test-Path -LiteralPath $dir)){ New-Item -ItemType Directory -Path $dir -Force | Out-Null }; Copy-Item -LiteralPath $_.FullName -Destination $dst -Force; $n++ }; Write-Host ('    ' + $n + ' donor sound payload(s) extracted')"
    if errorlevel 1 ( echo   ERROR: could not lay out the donor sound payloads. & exit /b 1 )
    rmdir /s /q "%PROJ%\zone_assets\_snd_dump"
)

REM  Now overlay what THIS project adds, every run, so an edit to either always
REM  takes: the extra alias rows, then the WAVs they point at.
echo   Staging this mod's own sounds ...
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$p='%PROJ%'; $base=Join-Path $p 'zone_assets\soundbank\mod.all.aliases.csv'; $add=Join-Path $p 'soundbank\mod.all.aliases.additions.csv'; $rows=@(Get-Content $base); $names=@{}; foreach($r in $rows[1..($rows.Count-1)]){ $names[($r -split ',')[0]] = $true }; $n=0; if(Test-Path $add){ foreach($r in @(Get-Content $add)[1..((@(Get-Content $add)).Count-1)]){ if($r.Trim() -eq ''){continue}; $nm=($r -split ',')[0]; if(-not $names.ContainsKey($nm)){ $rows += $r; $names[$nm]=$true; $n++ } } }; Set-Content -LiteralPath $base -Value $rows -Encoding ASCII; Write-Host ('    ' + $n + ' alias row(s) added, ' + ($rows.Count-1) + ' total'); $m=0; $src=Join-Path $p 'sound'; if(Test-Path $src){ Get-ChildItem -LiteralPath $src -Recurse -File | ForEach-Object { $rel=$_.FullName.Substring($p.Length+1); $dst=Join-Path (Join-Path $p 'zone_assets') $rel; $dir=Split-Path $dst -Parent; if(-not (Test-Path -LiteralPath $dir)){ New-Item -ItemType Directory -Path $dir -Force | Out-Null }; Copy-Item -LiteralPath $_.FullName -Destination $dst -Force; $m++ } }; Write-Host ('    ' + $m + ' sound payload(s) staged')"
if errorlevel 1 ( echo   ERROR: could not stage this mod's sounds. & exit /b 1 )

REM --- link -------------------------------------------------------------------
echo   Linking mod.ff ...
if exist "%PROJ%\zone_out" rmdir /s /q "%PROJ%\zone_out"

REM  zm_prison + zm_prison_patch are loaded for ELECTRIC CHERRY: the perk's
REM  models, fx, bottle weapon, HUD material and vision file are in zm_prison.ff,
REM  and BOTH halves of its script - maps\mp\zombies\_zm_perk_electric_cherry.gsc
REM  and the matching .csc - are in zm_prison_patch.ff.
REM
REM  🛑 Do NOT put REM lines between the caret-continued --load arguments below.
REM  cmd does not treat them as comments there - they are passed to the Linker as
REM  arguments, and it fails with: Could not find zone definition file for
REM  target "REM".
"%OAT_BASE%\Linker.exe" ^
  --load "%PROJ%\zone_source\base\mod.ff" ^
  --load "%BO2_DIR%\zone\all\ui_zm.ff" ^
  --load "%BO2_DIR%\zone\all\so_zsurvival_zm_transit.ff" ^
  --load "%BO2_DIR%\zone\all\so_zclassic_zm_prison.ff" ^
  --load "%BO2_DIR%\zone\all\so_zclassic_zm_buried.ff" ^
  --load "%BO2_DIR%\zone\all\so_zencounter_zm_buried.ff" ^
  --load "%BO2_DIR%\zone\all\zm_tomb.ff" ^
  --load "%BO2_DIR%\zone\all\zm_prison.ff" ^
  --load "%BO2_DIR%\zone\all\zm_prison_patch.ff" ^
  --base-folder "%PROJ%" ^
  --add-asset-search-path "%PROJ%\zone_assets" ^
  --add-source-search-path "%PROJ%\zone_source" ^
  --output-folder "%PROJ%\zone_out" ^
  mod

if errorlevel 1 (
    echo.
    echo   ERROR: link failed - mod.ff NOT replaced.
    exit /b 1
)

if not exist "%PROJ%\zone_out\mod.ff" (
    echo   ERROR: Linker reported success but produced no mod.ff.
    exit /b 1
)

copy /y "%PROJ%\zone_out\mod.ff" "%PROJ%\mod.ff" >nul

REM --- the sound banks --------------------------------------------------------
REM  🛑 THE LINKER BUILDS THE SOUND BANKS TOO, and until v1.39.0 this script threw
REM  them away with the rest of zone_out. That is why "you cannot add a sound to
REM  this mod" was believed for six releases.
REM
REM  A T6 sound is TWO halves and they live in different files:
REM      the ALIAS (name, volume, distances, looping) -> the soundbank asset in mod.ff
REM      the PAYLOAD (the actual audio)               -> mod.all.sabl / .sabs
REM  Both are generated from zone_assets\soundbank\mod.all.aliases.csv plus the
REM  WAV/FLAC tree under zone_assets\sound\, so BOTH have to be kept or the alias
REM  resolves to nothing and the sound is silent with no error logged.
REM
REM  Only mod.all is rebuilt. deathmachine_zm.all has no CSV in zone_assets, so the
REM  Linker copies it out of the donor untouched ("src: mod" in the link output)
REM  and deathmachine_zm.all.sabl at the project root is never regenerated.
for %%B in (mod.all.sabl mod.all.sabs) do (
    if exist "%PROJ%\zone_out\%%B" (
        copy /y "%PROJ%\zone_out\%%B" "%PROJ%\%%B" >nul
        for %%F in ("%PROJ%\%%B") do echo   %%B rebuilt: %%~zF bytes
    ) else (
        echo   NOTE: the Linker produced no %%B - the existing one is kept.
    )
)

rmdir /s /q "%PROJ%\zone_out"

for %%F in ("%PROJ%\mod.ff") do echo   mod.ff rebuilt: %%~zF bytes
echo   Now run build.bat to repack and deploy.
exit /b 0
