@echo off
setlocal EnableDelayedExpansion
REM ============================================================================
REM  build_ff.bat  -  rebuilds mod.ff with OpenAssetTools' Linker.
REM ----------------------------------------------------------------------------
REM  This is SEPARATE from build.bat and is only needed when you change something
REM  under zone_source\ or zone_assets\ (materials, images, and anything else that
REM  has to live inside a fastfile). Editing .gsc does NOT need this - raw script
REM  goes into mod.iwd via build.bat and never touches mod.ff.
REM
REM  HOW IT WORKS
REM    zone_source\base\mod.ff    the pristine fastfile this project shipped with.
REM                               It is the DONOR for the 3,510 assets already in
REM                               mod.ff (perk bottles, camos, weapons, xanims,
REM                               the baked scripts...). We have no source for
REM                               those, so the Linker copies them straight out of
REM                               this file. DO NOT DELETE IT - it is unrecoverable.
REM
REM  *** It must stay named exactly mod.ff, in its own folder. ***
REM  A T6 fastfile's internal zone name is part of how its compressed streams are
REM  read back; rename the file and OAT fails with "inflate of stream N failed:
REM  invalid block type". Same bytes, different filename = unloadable. That is why
REM  the donor lives in a subfolder instead of being called mod_base.ff.
REM    zone_source\mod_base.zone  that file's asset inventory, generated by the
REM                               Unlinker. Regenerate with:  build_ff.bat regen
REM    zone_source\mod_locations.zone  the assets this project adds.
REM    zone_assets\               material .json + image .iwi sources for them.
REM
REM  Always links from the donor, never from the current mod.ff, so repeated
REM  runs are deterministic and cannot compound.
REM ============================================================================

set "PROJ=%~dp0"
if "%PROJ:~-1%"=="\" set "PROJ=%PROJ:~0,-1%"

REM --- OpenAssetTools ---------------------------------------------------------
if not defined OAT_BASE set "OAT_BASE=H:\Claude\oat-windows"
if not exist "%OAT_BASE%\Linker.exe" (
    echo   ERROR: Linker.exe not found in "%OAT_BASE%".
    echo          Set OAT_BASE to your OpenAssetTools folder and re-run.
    exit /b 1
)

REM --- Black Ops II install (needed for stock assets referenced by our materials)
if not defined BO2_DIR set "BO2_DIR=F:\SteamLibrary\steamapps\common\Call of Duty Black Ops II"
if not exist "%BO2_DIR%\zone\all\ui_zm.ff" (
    echo   ERROR: ui_zm.ff not found under "%BO2_DIR%\zone\all".
    echo          Set BO2_DIR to your Black Ops II install folder and re-run.
    exit /b 1
)

if not exist "%PROJ%\zone_source\base\mod.ff" (
    echo   ERROR: zone_source\base\mod.ff is missing. It is the only copy of the
    echo          3,510 assets already in mod.ff and cannot be regenerated.
    exit /b 1
)

REM --- regen mode: rebuild mod_base.zone from mod_base.ff ----------------------
if /i "%~1"=="regen" (
    echo   Regenerating zone_source\mod_base.zone from base\mod.ff ...
    "%OAT_BASE%\Unlinker.exe" --include-assets keyvaluepairs -o "%PROJ%\zone_source\_regen" "%PROJ%\zone_source\base\mod.ff"
    if errorlevel 1 ( echo   ERROR: Unlinker failed. & exit /b 1 )
    copy /y "%PROJ%\zone_source\_regen\zone_source\mod.zone" "%PROJ%\zone_source\mod_base.zone" >nul
    rmdir /s /q "%PROJ%\zone_source\_regen"
    echo   mod_base.zone regenerated. Re-run build_ff.bat without 'regen' to link.
    exit /b 0
)

REM --- stage current .csc sources so mod.ff does not keep a stale copy ---------
REM  mod_base.zone (the donor's inventory) declares scripts/zm/zm_expanded.csc and
REM  the six per-map .csc files. T6 stores scripts in a fastfile as RAW TEXT, and
REM  the Linker resolves each declared asset from the asset search path FIRST and
REM  only falls back to a --load'ed fastfile. With nothing staged, every relink
REM  copied the donor's original .csc back in - so mod.ff kept shipping whatever
REM  those files looked like the day the mod was first built, no matter how much
REM  the working copies changed.
REM
REM  Unlike .gsc - which Plutonium's Mods menu happily runs raw out of mod.iwd
REM  (that is how quality_of_life.gsc works, and it is declared in no zone file)
REM  - client scripts are conventionally only loaded from the fastfile. Staging
REM  them here means the copy in mod.ff is always the current source, so it does
REM  not matter which of the two the engine ends up preferring.
echo   Staging current .csc sources into zone_assets ...
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$proj='%PROJ%'; $n=0; @('scripts','clientscripts') | ForEach-Object { Get-ChildItem -LiteralPath (Join-Path $proj $_) -Recurse -Filter *.csc -ErrorAction SilentlyContinue } | ForEach-Object { $rel=$_.FullName.Substring($proj.Length+1); $dst=Join-Path (Join-Path $proj 'zone_assets') $rel; $dir=Split-Path $dst -Parent; if(-not (Test-Path -LiteralPath $dir)){ New-Item -ItemType Directory -Path $dir -Force | Out-Null }; Copy-Item -LiteralPath $_.FullName -Destination $dst -Force; Write-Host ('    [stage] ' + $rel); $n++ }; Write-Host ('    ' + $n + ' client script(s) staged')"
if errorlevel 1 ( echo   ERROR: could not stage .csc sources. & exit /b 1 )

REM --- stage the sound bank source --------------------------------------------
REM  A T6 sound alias is built from a 60-column CSV plus the WAV/FLAC it names in
REM  its FileSource column. To add ONE alias the Linker still has to rebuild the
REM  WHOLE bank, so it needs the full table and every payload the donor already
REM  had - 1,691 aliases over 249 distinct audio files.
REM
REM  Both come straight back out of the donor, so none of it is checked in:
REM      Unlinker --include-assets soundbank --search-path <base>  ->  the CSV
REM                                                                    AND the audio
REM  🛑 --search-path must point at zone_source\base, never at the project root.
REM  The root mod.all.sabl is a BUILD OUTPUT once this script has run; dumping from
REM  it would feed each build its own previous output and compound. Same rule as
REM  linking from base\mod.ff instead of the live mod.ff.
REM
REM  🛑 DO NOT "FIX" THE DOUBLED EXTENSION. The dumped files are named
REM  foo.snd.wav.wav and the CSV's FileSource says foo.snd.wav.wav, and BOTH ARE
REM  CORRECT - that doubled name is this bank's genuine stored value, not something the
REM  Unlinker added. It writes the CSV out verbatim. Verified by dumping the donor two
REM  different ways (with and without --search-path) and getting the identical string.
REM
REM  This was got wrong once in each direction and the check that settles it is always
REM  the same: dump the donor and the freshly built mod.ff the SAME way and diff the
REM  FileSource column. Zero differing rows means the table round-tripped. Anything else
REM  means every alias whose audio lives in a stock bank - about 930 of the 1,179, since
REM  only ~250 have a payload inside mod.all.sabl - is looking up a path that no bank
REM  has, which is silent with no error anywhere.
REM
REM  Also: wipe zone_assets\sound and zone_assets\soundbank before testing a change
REM  here. A half-stripped tree left over from a previous attempt reads as a build bug
REM  that is not in the build.
if not exist "%PROJ%\zone_assets\soundbank\mod.all.aliases.csv" (
    echo   Extracting the donor sound bank ^(first run only, ~250 files^) ...
    if exist "%PROJ%\zone_assets\_snd_dump" rmdir /s /q "%PROJ%\zone_assets\_snd_dump"
    "%OAT_BASE%\Unlinker.exe" --include-assets soundbank --search-path "%PROJ%\zone_source\base" -o "%PROJ%\zone_assets\_snd_dump" "%PROJ%\zone_source\base\mod.ff" >nul
    if errorlevel 1 ( echo   ERROR: could not extract the donor sound bank. & exit /b 1 )
    "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$p='%PROJ%'; $d=Join-Path $p 'zone_assets\_snd_dump'; New-Item -ItemType Directory -Force -Path (Join-Path $p 'zone_assets\soundbank') | Out-Null; Copy-Item (Join-Path $d 'soundbank\mod.all.aliases.csv') (Join-Path $p 'zone_assets\soundbank\mod.all.aliases.csv') -Force; $n=0; Get-ChildItem -LiteralPath (Join-Path $d 'sound') -Recurse -File | ForEach-Object { $rel=$_.FullName.Substring((Join-Path $d '').Length); $dst=Join-Path (Join-Path $p 'zone_assets') $rel; $dir=Split-Path $dst -Parent; if(-not (Test-Path -LiteralPath $dir)){ New-Item -ItemType Directory -Path $dir -Force | Out-Null }; Copy-Item -LiteralPath $_.FullName -Destination $dst -Force; $n++ }; Write-Host ('    ' + $n + ' donor sound payload(s) extracted')"
    if errorlevel 1 ( echo   ERROR: could not lay out the donor sound payloads. & exit /b 1 )
    rmdir /s /q "%PROJ%\zone_assets\_snd_dump"
)

REM  Now overlay what THIS project adds, every run, so an edit to either always
REM  takes: the extra alias rows, then the WAVs they point at.
REM
REM  🛑 THE OVERLAY REPLACES BY NAME. IT USED TO ONLY APPEND, AND THAT MADE EDITING A
REM  SHIPPED ALIAS A SILENT NO-OP - the exact failure this file's own header warns
REM  about, one level up.
REM
REM  zone_assets\soundbank\mod.all.aliases.csv is a CACHE, regenerated from the donor
REM  only when it is missing. Once an addition had been appended to it, that appended
REM  copy was the row every later build used, and the version in
REM  soundbank\mod.all.aliases.additions.csv - the file this project actually treats as
REM  source - was skipped forever because its Name was "already present". v1.42.0's
REM  Vulture pickup fix was a one-column change to an existing row: build_ff printed
REM  "0 alias row(s) added", linked happily, and shipped the old table. Nothing in any
REM  log said otherwise.
REM
REM  So: the additions file now OWNS every alias name it mentions. Each build drops
REM  all cached rows carrying a name the additions file uses, then appends the
REM  additions verbatim.
REM
REM  🛑 DROP-AND-APPEND, NOT REPLACE-IN-PLACE, BECAUSE AN ALIAS CAN HAVE VARIANTS.
REM  zmb_rand_perk_sparks_top is THREE rows sharing one Name - that is how T6 does
REM  randomised one-shots, the engine picks a row per play. A name-keyed replace
REM  collapses all three into whichever came last, silently turning a varied spark
REM  into the same click every time. Keyed on Name+FileSource instead, editing a
REM  FileSource would strand the old row as a phantom variant. Dropping by name and
REM  re-appending the whole group is the only shape that is right in both cases.
REM
REM  If you would rather start clean, deleting the cached CSV also works - but that
REM  should be a convenience, not the only way an edit can take.
echo   Staging this mod's own sounds ...
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$p='%PROJ%'; $base=Join-Path $p 'zone_assets\soundbank\mod.all.aliases.csv'; $add=Join-Path $p 'soundbank\mod.all.aliases.additions.csv'; $rows=@(Get-Content $base); $out=@($rows[0]); $mine=@(); $own=@{}; if(Test-Path $add){ $ar=@(Get-Content $add); foreach($r in $ar[1..($ar.Count-1)]){ if($r.Trim() -eq ''){continue}; $mine += $r; $own[($r -split ',')[0]]=$true } }; $drop=0; for($i=1;$i -lt $rows.Count;$i++){ if($own.ContainsKey((($rows[$i]) -split ',')[0])){ $drop++ } else { $out += $rows[$i] } }; $out += $mine; Set-Content -LiteralPath $base -Value $out -Encoding ASCII; Write-Host ('    ' + $mine.Count + ' alias row(s) from this mod (' + $own.Count + ' distinct names, ' + $drop + ' cached row(s) replaced), ' + ($out.Count-1) + ' total'); $m=0; $src=Join-Path $p 'sound'; if(Test-Path $src){ Get-ChildItem -LiteralPath $src -Recurse -File | ForEach-Object { $rel=$_.FullName.Substring($p.Length+1); $dst=Join-Path (Join-Path $p 'zone_assets') $rel; $dir=Split-Path $dst -Parent; if(-not (Test-Path -LiteralPath $dir)){ New-Item -ItemType Directory -Path $dir -Force | Out-Null }; Copy-Item -LiteralPath $_.FullName -Destination $dst -Force; $m++ } }; Write-Host ('    ' + $m + ' sound payload(s) staged')"
if errorlevel 1 ( echo   ERROR: could not stage this mod's sounds. & exit /b 1 )

REM --- stage the sound bank's DUCKS -------------------------------------------
REM  A "duck" is a mixer snapshot: while an alias that names one is playing, every
REM  other DuckGroup is attenuated by the amounts in the .duk. It is a real,
REM  audible part of some effects - Origins' zmb_zombieblood_loop names
REM  zmb_tomb_zombieblood, which drops ambience to 25%% and weapons/impacts to 50%%
REM  for the whole 30 seconds, and that muffling IS the zombie-blood soundscape.
REM
REM  🛑 THE DONOR mod.all HAS NO DUCKLIST AT ALL - zero of its 1,691 aliases carry
REM  a Duck value - so nothing staged one before v1.65.0. An alias that names a
REM  duck the bank cannot supply is a HARD LINK ERROR, not a silent no-op:
REM      Unable to find .duk file for {} in ducklist for sound bank {}
REM  (string lifted straight out of Linker.exe). So the ducklist and the .duk
REM  files have to travel together with the alias rows that reference them.
REM
REM  Layout is the Linker's own, confirmed from its format strings:
REM      soundbank\<bank>.ducklist.csv     one column, header "name"
REM      soundbank\ducks\<name>.duk        the JSON snapshot
REM  Both come from soundbank\ at the project root (source, git-tracked) and are
REM  copied verbatim into zone_assets\soundbank\ every run, like the alias rows.
REM
REM  📝 Duck names are mod-private (zmqol_*) for the same reason alias names are:
REM  mod.ff loads ahead of every map, so a stock name here would put a second
REM  definition in front of the map that owns it.
echo   Staging this mod's sound-bank ducks ...
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$p='%PROJ%'; $n=0; $srcList=Join-Path $p 'soundbank\mod.all.ducklist.csv'; $dstDir=Join-Path $p 'zone_assets\soundbank'; if(Test-Path $srcList){ if(-not (Test-Path -LiteralPath $dstDir)){ New-Item -ItemType Directory -Path $dstDir -Force | Out-Null }; Copy-Item -LiteralPath $srcList -Destination (Join-Path $dstDir 'mod.all.ducklist.csv') -Force; $n++ }; $srcDucks=Join-Path $p 'soundbank\ducks'; if(Test-Path $srcDucks){ $dd=Join-Path $dstDir 'ducks'; if(-not (Test-Path -LiteralPath $dd)){ New-Item -ItemType Directory -Path $dd -Force | Out-Null }; Get-ChildItem -LiteralPath $srcDucks -File -Filter *.duk | ForEach-Object { Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $dd $_.Name) -Force; $n++ } }; Write-Host ('    ' + $n + ' duck file(s) staged')"
if errorlevel 1 ( echo   ERROR: could not stage this mod's ducks. & exit /b 1 )

REM --- link -------------------------------------------------------------------
echo   Linking mod.ff ...
if exist "%PROJ%\zone_out" rmdir /s /q "%PROJ%\zone_out"

REM  zm_buried + zm_buried_patch are loaded for VULTURE AID, the same way and for
REM  the same reasons: the vending machines, bottle weapon, ammo/points pickups,
REM  HUD shader, vision filter and all fifteen fx are in zm_buried.ff, and the
REM  client half of its script is in zm_buried_patch.ff. Its SERVER half is not
REM  needed here - that ships as raw GSC in mod.iwd, like PhD Flopper's.
REM
REM  zm_prison + zm_prison_patch are loaded for ELECTRIC CHERRY: the perk's
REM  models, fx, bottle weapon, HUD material and vision file are in zm_prison.ff,
REM  and BOTH halves of its script - maps\mp\zombies\_zm_perk_electric_cherry.gsc
REM  and the matching .csc - are in zm_prison_patch.ff.
REM
REM  zm_highrise is loaded for WHO'S WHO. Only four assets are taken from it -
REM  the bottle weapon, its view/world models and the HUD icon material - and
REM  they all live in zm_highrise.ff, so the _patch is NOT needed here. Who's Who
REM  needs no client script of its own: _zm_chugabud.gsc is a CORE module and its
REM  client-side extras (whos_who_audio/_filter, the clone glow shader, the
REM  zm_whos_who visionset) are all gated behind level.whos_who_client_setup and
REM  level.vsmgr_prio_visionset_zm_whos_who, which ONLY Die Rise sets. Off Die
REM  Rise the perk self-gates down to one clientfield and no client assets.
REM
REM  🛑🛑 --load ORDER IS NOT COSMETIC. IT DECIDES WHICH COPY OF A SHARED STOCK
REM  ASSET THIS MOD SHIPS - AND mod.ff LOADS BEFORE EVERY MAP, SO THAT COPY WINS
REM  ON EVERY MAP, INCLUDING THE ONES THE ASSET IS NATIVE TO.
REM
REM  The Linker resolves each asset from the FIRST --load'ed fastfile that carries
REM  a real definition of it (a `type,,name` reference carries no data, so it keeps
REM  looking). Two fastfiles can hold DIFFERENT bytes under the SAME name - stock
REM  ships per-map shader permutations and per-map fx rebuilds - so whichever one
REM  is listed first silently becomes the version every map gets.
REM
REM  🔴 THIS SHIPPED BROKEN FOR SEVERAL VERSIONS AND THE USER REPORTED IT (v1.62.7):
REM  Electric Cherry's zap on zombies rendered as a bright blown-out blob instead of
REM  lightning arcs - and it was wrong on Mob of the Dead and Origins TOO, where the
REM  perk is stock and this mod adds nothing. Measured cause: so_zsurvival_zm_transit
REM  was loaded 3rd and zm_prison 8th, so mod.ff baked TranZit-survival's copy of
REM  techniqueset effect_zeqqz943 - the shader for the tesla-shock flare materials -
REM  and overrode the correct one everywhere.
REM
REM      techniqueset effect_zeqqz943, 4928 bytes in every case:
REM        zm_prison / zm_tomb / zm_highrise   503675916d7525ca   <- all identical
REM        so_zsurvival_zm_transit             b6c22239cf5774a5   <- what shipped
REM
REM  🛑 SO: zm_prison.ff AND zm_prison_patch.ff MUST STAY AHEAD OF EVERY so_*.ff.
REM  Mob of the Dead is Electric Cherry's home map, so loading it first makes the
REM  perk's whole chain - the 5 alcatraz cherry fx, the 3 tesla fx, the bottle
REM  weapon and its two xmodels, the HUD + minimap icons, the vision file and every
REM  lightning material/techset under them - come from ONE canonical donor instead
REM  of being scavenged across four. Verified: the built asset list is byte-identical
REM  before and after (nothing re-owned, nothing dropped), 0 errors, same 34 sound
REM  warnings; 64 assets change donor, of which 20 actually differ in content and
REM  every one of those is either Electric Cherry's own or in the tesla fx chain.
REM
REM  📝 Known residual, NOT introduced by this ordering - three generic lit-model
REM  techsets (mc_lit_sm_r0c0d0n0_33ffej1u, _r0c0n0x0_q361191u, _t0c0n0_9qf6e4qj)
REM  differ on EVERY map, so no single donor is right for all of them. mod.ff has
REM  always overridden them globally; this only changes which map they happen to
REM  match. The real repair is to stop owning them at all - QUEUE §0f item 4.
REM
REM  🛑 Do NOT put REM lines between the caret-continued --load arguments below.
REM  cmd does not treat them as comments there - they are passed to the Linker as
REM  arguments, and it fails with: Could not find zone definition file for
REM  target "REM".
"%OAT_BASE%\Linker.exe" ^
  --load "%PROJ%\zone_source\base\mod.ff" ^
  --load "%BO2_DIR%\zone\all\ui_zm.ff" ^
  --load "%BO2_DIR%\zone\all\zm_prison.ff" ^
  --load "%BO2_DIR%\zone\all\zm_prison_patch.ff" ^
  --load "%BO2_DIR%\zone\all\so_zsurvival_zm_transit.ff" ^
  --load "%BO2_DIR%\zone\all\so_zclassic_zm_prison.ff" ^
  --load "%BO2_DIR%\zone\all\so_zclassic_zm_buried.ff" ^
  --load "%BO2_DIR%\zone\all\so_zencounter_zm_buried.ff" ^
  --load "%BO2_DIR%\zone\all\zm_tomb.ff" ^
  --load "%BO2_DIR%\zone\all\zm_buried.ff" ^
  --load "%BO2_DIR%\zone\all\zm_buried_patch.ff" ^
  --load "%BO2_DIR%\zone\all\zm_highrise.ff" ^
  --load "%BO2_DIR%\zone\all\zm_transit.ff" ^
  --load "%BO2_DIR%\zone\all\so_zclassic_zm_transit.ff" ^
  --load "%PROJ%\zone_source\ww_donor\mod.ff" ^
  --load "%PROJ%\zone_source\pro7_donor\mod.ff" ^
  --base-folder "%PROJ%" ^
  --add-asset-search-path "%PROJ%\zone_assets" ^
  --add-source-search-path "%PROJ%\zone_source" ^
  --output-folder "%PROJ%\zone_out" ^
  mod

if errorlevel 1 (
    echo.
    echo   ERROR: link failed - mod.ff NOT replaced.
    exit /b 1
)

if not exist "%PROJ%\zone_out\mod.ff" (
    echo   ERROR: Linker reported success but produced no mod.ff.
    exit /b 1
)

copy /y "%PROJ%\zone_out\mod.ff" "%PROJ%\mod.ff" >nul

REM --- the sound banks --------------------------------------------------------
REM  🛑 THE LINKER BUILDS THE SOUND BANKS TOO, and until v1.39.0 this script threw
REM  them away with the rest of zone_out. That is why "you cannot add a sound to
REM  this mod" was believed for six releases.
REM
REM  A T6 sound is TWO halves and they live in different files:
REM      the ALIAS (name, volume, distances, looping) -> the soundbank asset in mod.ff
REM      the PAYLOAD (the actual audio)               -> mod.all.sabl / .sabs
REM  Both are generated from zone_assets\soundbank\mod.all.aliases.csv plus the
REM  WAV/FLAC tree under zone_assets\sound\, so BOTH have to be kept or the alias
REM  resolves to nothing and the sound is silent with no error logged.
REM
REM  Only mod.all is rebuilt. deathmachine_zm.all has no CSV in zone_assets, so the
REM  Linker copies it out of the donor untouched ("src: mod" in the link output)
REM  and deathmachine_zm.all.sabl at the project root is never regenerated.
for %%B in (mod.all.sabl mod.all.sabs) do (
    if exist "%PROJ%\zone_out\%%B" (
        copy /y "%PROJ%\zone_out\%%B" "%PROJ%\%%B" >nul
        for %%F in ("%PROJ%\%%B") do echo   %%B rebuilt: %%~zF bytes
    ) else (
        echo   NOTE: the Linker produced no %%B - the existing one is kept.
    )
)

rmdir /s /q "%PROJ%\zone_out"

for %%F in ("%PROJ%\mod.ff") do echo   mod.ff rebuilt: %%~zF bytes
echo   Now run build.bat to repack and deploy.
exit /b 0
