// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include maps\mp\_utility;
#include common_scripts\utility;
#include maps\mp\zombies\_zm_utility;
#include maps\mp\gametypes_zm\_hud_util;

init()
{
    qol_opt_dvar( "rapid_fire", "0" );
    qol_opt_dvar( "night_mode", "0" );
    qol_opt_dvar( "character", "0" );
    qol_opt_dvar( "disable_player_quotes", "1" );
    qol_opt_dvar( "coop_pause", "0" );
    qol_opt_dvar( "hud_master", "1" );
    qol_opt_dvar( "hud_all", "0" );
    qol_opt_dvar( "hud_timer", "1" );
    qol_opt_dvar( "hud_round_timer", "1" );
    qol_opt_dvar( "hud_health_bar", "1" );
    qol_opt_dvar( "hud_remaining", "1" );
    qol_opt_dvar( "hud_zone", "0" );
    qol_opt_dvar( "hud_color", "1 1 1" );
    qol_opt_dvar( "hud_color_health", "1 1 1" );
    qol_opt_dvar( "hud_color_timer", "1 1 0" );
    qol_opt_dvar( "hud_color_round_timer", "0.4 0.75 1" );
    qol_opt_dvar( "anim_pap_camo_mob", "1" );
    qol_opt_dvar( "anim_pap_camo_buried", "1" );
    qol_opt_dvar( "anim_pap_camo_origins", "1" );
    qol_opt_dvar( "no_power", "0" );
    qol_opt_dvar( "lod_fix", "1" );
    level thread qol_opt_coop_pause();
    level thread qol_opt_round_clock();
    level thread qol_opt_no_power();
    level thread qol_opt_lod_fix();
    level thread qol_opt_roundcounter_master();
    level thread qol_opt_connect_loop();
}

qol_opt_roundcounter_master()
{
    level endon( "end_game" );
    n_prev = 1;

    for (;;)
    {
        wait 0.25;
        n_on = getdvarintdefault( "hud_master", 1 );

        if ( !isdefined( level.zmqol_roundcounter ) )
        {
            n_prev = n_on;
            continue;
        }

        if ( !n_on )
        {
            level.zmqol_roundcounter.alpha = 0;
        }
        else if ( !n_prev )
        {
            level.zmqol_roundcounter.alpha = 1;
        }

        n_prev = n_on;
    }
}

qol_opt_lod_fix()
{
    level endon( "end_game" );
    n_prev = -1;

    for (;;)
    {
        n_on = getdvarintdefault( "lod_fix", 1 );

        if ( n_on != n_prev )
        {
            n_prev = n_on;

            if ( n_on )
            {
                setdvar( "r_lodBiasRigid", "-1000" );
                setdvar( "r_lodBiasSkinned", "-1000" );
            }
            else
            {
                setdvar( "r_lodBiasRigid", "0" );
                setdvar( "r_lodBiasSkinned", "0" );
            }

            setdvar( "r_lodScaleRigid", "1" );
            setdvar( "r_lodScaleSkinned", "1" );
        }

        wait 1;
    }
}

qol_opt_dvar( str_dvar, str_default )
{
    if ( getdvar( str_dvar ) == "" )
        setdvar( str_dvar, str_default );
}

qol_opt_connect_loop()
{
    for (;;)
    {
        level waittill( "connected", player );
        player thread qol_opt_player_init();
    }
}

qol_opt_player_init()
{
    self endon( "disconnect" );
    b_first = 1;

    for (;;)
    {
        self waittill( "spawned_player" );

        if ( !b_first )
            continue;

        b_first = 0;
        self thread qol_opt_cherry_sound();
        self thread qol_opt_rapid_fire();
        self thread qol_opt_player_quotes();
        self thread qol_opt_night_mode();
        self thread qol_opt_character();
        self thread qol_opt_hud_watcher();
    }
}

qol_opt_rapid_fire()
{
    self endon( "disconnect" );
    level endon( "end_game" );

    for (;;)
    {
        if ( !getdvarintdefault( "rapid_fire", 0 ) )
        {
            wait 0.25;
            continue;
        }

        self waittill( "weapon_fired", str_fired );

        if ( !getdvarintdefault( "rapid_fire", 0 ) )
            continue;

        a_primaries = self getweaponslistprimaries();

        if ( !isdefined( a_primaries ) || a_primaries.size < 2 )
            continue;

        foreach ( str_weapon in a_primaries )
        {
            if ( str_weapon == str_fired )
                continue;

            self switchtoweapon( str_weapon );
            wait 0.05;
            self switchtoweapon( str_fired );
            self setspawnweapon( str_fired );
            break;
        }
    }
}

qol_opt_cherry_sound()
{
    self endon( "disconnect" );
    level endon( "end_game" );

    if ( level.script == "zm_prison" || level.script == "zm_tomb" )
        return;

    for (;;)
    {
        self waittill( "electric_cherry_start" );
        self playsound( "zmqol_cherry_zap" );
    }
}

qol_opt_player_quotes()
{
    self endon( "disconnect" );
    level endon( "end_game" );

    for (;;)
    {
        if ( getdvarintdefault( "disable_player_quotes", 1 ) )
            self.isspeaking = 1;

        wait 0.5;
    }
}

qol_opt_night_mode()
{
    self endon( "disconnect" );
    level endon( "end_game" );

    if ( !isdefined( level.qol_default_exposure ) )
    {
        level.qol_default_exposure = getdvar( "r_exposureValue" );
        level.qol_default_sunlight = getdvar( "r_lightTweakSunLight" );
        level.qol_default_skyfactor = getdvar( "r_sky_intensity_factor0" );
    }

    b_on = 0;

    for (;;)
    {
        b_want = getdvarintdefault( "night_mode", 0 );

        if ( b_want && !b_on )
        {
            b_on = 1;
            self qol_opt_night_on();
        }
        else if ( !b_want && b_on )
        {
            b_on = 0;
            self qol_opt_night_off();
        }

        wait 0.25;
    }
}

qol_opt_night_on()
{
    self setclientdvar( "r_dof_enable", 0 );
    self setclientdvar( "r_enablePlayerShadow", 1 );
    self setclientdvar( "r_skyTransition", 1 );
    self setclientdvar( "sm_sunquality", 2 );
    self setclientdvar( "vc_fbm", "0 0 0 0" );
    self setclientdvar( "vc_fsm", "1 1 1 1" );
    self setclientdvar( "r_filmUseTweaks", 1 );
    self setclientdvar( "r_bloomTweaks", 1 );
    self setclientdvar( "r_exposureTweak", 1 );
    self setclientdvar( "vc_rgbh", "0.1 0 0.3 0" );
    self setclientdvar( "vc_yl", "0 0 0.25 0" );
    self setclientdvar( "vc_yh", "0.02 0 0.1 0" );
    self setclientdvar( "vc_rgbl", "0.02 0 0.1 0" );
    self setclientdvar( "r_lightTweakSunLight", 1 );
    self setclientdvar( "r_sky_intensity_factor0", 0 );
    n_exposure = 3.9;

    if ( level.script == "zm_buried" )
        n_exposure = 3.5;
    else if ( level.script == "zm_tomb" )
        n_exposure = 4;
    else if ( level.script == "zm_nuked" )
        n_exposure = 5.6;
    else if ( level.script == "zm_highrise" )
        n_exposure = 3.9;

    self setclientdvar( "r_exposureValue", n_exposure );
    self thread qol_opt_night_visual_fix();
    println( "[zm_qol] night_mode ON - ported from _zm_nightmode.gsc, exposure " + n_exposure );
}

qol_opt_night_visual_fix()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "disable_nightmode" );

    if ( level.script == "zm_buried" )
    {
        for (;;)
        {
            self setclientdvar( "r_lightTweakSunLight", 1 );
            self setclientdvar( "r_sky_intensity_factor0", 0 );
            wait 0.2;
        }
    }
    else if ( level.script == "zm_prison" || level.script == "zm_tomb" )
    {
        for (;;)
        {
            for ( i = float( getdvar( "r_lightTweakSunLight" ) ); i >= 0; i = ( i - 0.2 ) )
            {
                self setclientdvar( "r_lightTweakSunLight", i );
                wait 0.2;
            }

            wait 0.2;
        }
    }
}

qol_opt_night_off()
{
    self notify( "disable_nightmode" );
    self setclientdvar( "r_lightGridEnableTweaks", 0 );
    self setclientdvar( "r_lightGridIntensity", 1 );
    self setclientdvar( "r_filmUseTweaks", 0 );
    self setclientdvar( "r_bloomTweaks", 0 );
    self setclientdvar( "r_exposureTweak", 0 );
    self setclientdvar( "vc_rgbh", "0 0 0 0" );
    self setclientdvar( "vc_yl", "0 0 0 0" );
    self setclientdvar( "vc_yh", "0 0 0 0" );
    self setclientdvar( "vc_rgbl", "0 0 0 0" );

    if ( isdefined( level.qol_default_exposure ) )
    {
        self setclientdvar( "r_exposureValue", level.qol_default_exposure );
        self setclientdvar( "r_lightTweakSunLight", level.qol_default_sunlight );
        self setclientdvar( "r_sky_intensity_factor0", level.qol_default_skyfactor );
    }
}

qol_opt_character()
{
    self endon( "disconnect" );

    if ( !isdefined( level.givecustomcharacters ) )
        return;

    if ( isdefined( level.force_team_characters ) && level.force_team_characters == 1 )
        return;

    if ( level.script == "zm_tomb" || level.script == "zm_prison" )
        return;

    n_last = -1;

    for (;;)
    {
        n_want = getdvarintdefault( "character", 0 );

        if ( n_want > 0 && n_want != n_last )
        {
            n_last = n_want;
            self.characterindex = ( n_want - 1 ) % 4;
            self.favorite_wall_weapons_list = [];
            self [[ level.givecustomcharacters ]]();
        }

        wait 0.5;
    }
}

qol_opt_coop_pause()
{
    level endon( "end_game" );
    b_paused = 0;

    for (;;)
    {
        wait 0.5;
        b_want = getdvarintdefault( "coop_pause", 0 );

        if ( b_want == b_paused )
            continue;

        a_players = get_players();

        if ( a_players.size < 2 )
            continue;

        if ( b_want )
        {
            if ( get_round_enemy_array().size + level.zombie_total != 0 )
            {
                level iprintln( "^3[zm_qol] ^7pausing at the start of the next round" );
                level waittill( "end_of_round" );
            }

            b_paused = 1;
            level iprintln( "^3[zm_qol] ^7PAUSED - coop_pause 0 to resume" );
        }
        else
        {
            b_paused = 0;
            level iprintln( "^3[zm_qol] ^7resumed" );
        }

        foreach ( player in a_players )
            player setclientdvar( "ai_disableSpawn", b_paused );
    }
}

qol_opt_no_power()
{
    if ( level.script != "zm_transit" )
        return;

    if ( !getdvarintdefault( "no_power", 0 ) )
        return;

    flag_wait( "start_zombie_round_logic" );

    if ( !isdefined( level.zombie_include_buildables ) )
        return;

    if ( isdefined( level.zombie_include_buildables["turbine"] ) )
        level.zombie_include_buildables["turbine"].triggerthink = ::qol_opt_nullptr;

    if ( isdefined( level.zombie_include_buildables["jetgun_zm"] ) )
        level.zombie_include_buildables["jetgun_zm"].triggerthink = ::qol_opt_nullptr;

    level iprintln( "^3[zm_qol] ^7no_power - turbine and jet gun disabled" );
}

qol_opt_nullptr()
{

}

qol_opt_hud_watcher()
{
    self endon( "disconnect" );
    level endon( "end_game" );
    flag_wait( "initial_blackscreen_passed" );
    str_prev_color = "1 1 1";
    str_prev_color_timer = "1 1 0";
    str_prev_color_round = "0.4 0.75 1";
    n_prev_master = -1;
    n_tick = 0;

    for (;;)
    {
        b_all = getdvarintdefault( "hud_all", 0 );
        b_master = getdvarintdefault( "hud_master", 1 );
        n_tick++;

        if ( b_master != n_prev_master || ( !b_master && n_tick % 8 == 0 ) )
        {
            n_prev_master = b_master;
            self setclientuivisibilityflag( "hud_visible", b_master );
        }

        self qol_opt_show( self.qol_hud_timer, b_master && ( b_all || getdvarintdefault( "hud_timer", 1 ) ) );
        self qol_opt_zone_hud( b_master && ( b_all || getdvarintdefault( "hud_zone", 0 ) ) );
        self qol_opt_round_timer_hud( b_master && ( b_all || getdvarintdefault( "hud_round_timer", 1 ) ) );
        str_color = getdvar( "hud_color" );

        if ( str_color != str_prev_color )
        {
            str_prev_color = str_color;
            v_color = qol_opt_parse_color( str_color );

            if ( isdefined( v_color ) )
            {
                self qol_opt_tint( self.zombietext, v_color );
                self qol_opt_tint( self.qol_hud_zone, v_color );
            }
        }

        str_color_timer = getdvar( "hud_color_timer" );

        if ( str_color_timer != str_prev_color_timer )
        {
            str_prev_color_timer = str_color_timer;
            v_color = qol_opt_parse_color( str_color_timer );

            if ( isdefined( v_color ) )
                self qol_opt_tint( self.qol_hud_timer, v_color );
        }

        str_color_round = getdvar( "hud_color_round_timer" );

        if ( str_color_round != str_prev_color_round )
        {
            str_prev_color_round = str_color_round;
            v_color = qol_opt_parse_color( str_color_round );

            if ( isdefined( v_color ) )
                self qol_opt_tint( self.qol_hud_roundtimer, v_color );
        }

        wait 0.25;
    }
}

qol_opt_parse_color( str_color )
{
    if ( !isdefined( str_color ) || str_color == "" )
        return undefined;

    a_parts = strtok( str_color, " " );

    if ( !isdefined( a_parts ) || a_parts.size != 3 )
        return undefined;

    return ( string_to_float( a_parts[0] ), string_to_float( a_parts[1] ), string_to_float( a_parts[2] ) );
}

qol_opt_show( e_hud, b_visible )
{
    if ( !isdefined( e_hud ) )
        return;

    if ( b_visible )
        e_hud.alpha = 1;
    else
        e_hud.alpha = 0;
}

qol_opt_tint( e_hud, v_color )
{
    if ( !isdefined( e_hud ) )
        return;

    e_hud.color = v_color;
}

qol_opt_zone_hud( b_on )
{
    if ( !b_on )
    {
        if ( isdefined( self.qol_hud_zone ) )
        {
            self.qol_hud_zone destroy();
            self.qol_hud_zone = undefined;
        }

        return;
    }

    if ( !isdefined( self.qol_hud_zone ) )
    {
        self.qol_hud_zone = self createfontstring( "hudsmall", 1.2 );
        self.qol_hud_zone setpoint( "LEFT", "BOTTOM_LEFT", -45, -24 );
        self.qol_hud_zone.hidewheninmenu = 1;
    }

    str_zone = "";

    if ( isdefined( self.zone_name ) )
        str_zone = self.zone_name;

    self.qol_hud_zone settext( str_zone );
}

qol_opt_round_timer_hud( b_on )
{
    if ( !b_on )
    {
        if ( isdefined( self.qol_hud_roundtimer ) )
        {
            self.qol_hud_roundtimer destroy();
            self.qol_hud_roundtimer = undefined;
        }

        return;
    }

    if ( !isdefined( self.qol_hud_roundtimer ) )
    {
        self.qol_hud_roundtimer = self createfontstring( "hudsmall", 1.2 );
        self.qol_hud_roundtimer.alignx = "left";
        self.qol_hud_roundtimer.aligny = "top";
        self.qol_hud_roundtimer.horzalign = "left";
        self.qol_hud_roundtimer.vertalign = "user_top";
        self.qol_hud_roundtimer.x = -64;
        self.qol_hud_roundtimer.y = 12;
        self.qol_hud_roundtimer.color = ( 0.4, 0.75, 1 );
        self.qol_hud_roundtimer.hidewheninmenu = 1;

        if ( isdefined( level.qol_round_start_time ) )
            self.qol_hud_roundtimer settimerup( ( gettime() - level.qol_round_start_time ) / 1000 );
        else
            self.qol_hud_roundtimer settimerup( 0 );
    }
}

qol_opt_round_clock()
{
    level endon( "end_game" );

    for (;;)
    {
        level waittill( "start_of_round" );
        level.qol_round_start_time = gettime();

        foreach ( player in get_players() )
        {
            if ( isdefined( player.qol_hud_roundtimer ) )
                player.qol_hud_roundtimer settimerup( 0 );
        }
    }
}
