// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include common_scripts\utility;
#include clientscripts\mp\_utility;
#include clientscripts\mp\zombies\_zm_utility;
#include clientscripts\mp\zombies\_zm_perks;
#include clientscripts\mp\zombies\_zm_perk_divetonuke;
#include clientscripts\mp\zombies\_zm_perk_vulture;
#include clientscripts\mp\_visionset_mgr;
#include clientscripts\mp\_ambientpackage;
#include clientscripts\mp\_music;
#include clientscripts\mp\_audio;
#include clientscripts\mp\_fx;
#include clientscripts\mp\_filter;
#include clientscripts\mp\zombies\_zm;

#using_animtree("qolwf_perk_random");

main()
{
    scriptmodelsuseanimtree( #animtree );
    replacefunc( clientscripts\mp\zombies\_zm_perks::perks_register_clientfield, ::perks_register_clientfield );
    replacefunc( clientscripts\mp\zombies\_zm::init_client_flag_callback_funcs, ::init_client_flag_callback_funcs );
    replacefunc( clientscripts\mp\_utility_code::struct_class_init, ::struct_class_init );
    zmqol_enable_fire_sale();
    zmqol_enable_blood_money();
    zmqol_mp_weapons_init();
    perks();
    level thread zmqol_testsound_watch();
}

zmqol_mp_weapons_init()
{
    if ( !getdvarintdefault( "zmqol_mp_weapons", 1 ) )
        return;

    clientscripts\mp\zombies\_zm_weapons::include_weapon( "sig556_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "sa58_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "mk48_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "qbb95_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "mp7_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "vector_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "insas_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "peacekeeper_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "crossbow_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "as50_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "titus6_zm" );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "sig556_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "sa58_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "mk48_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "qbb95_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "mp7_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "vector_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "insas_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "peacekeeper_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "crossbow_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "as50_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "titus6_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "vector_extclip_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "vector_extclip_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "gl_sig556_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "sf_sa58_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "crossbow_explosive_bolt_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "crossbow_explosive_bolt_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "mk_titus6_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "mk_titus6_upgraded_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "titus6_explosive_dart_zm", 0 );
    clientscripts\mp\zombies\_zm_weapons::include_weapon( "titus6_explosive_dart_upgraded_zm", 0 );
}

zmqol_enable_blood_money()
{
    clientscripts\mp\zombies\_zm_utility::include_powerup( "bonus_points_player" );
}

zmqol_enable_fire_sale()
{
    map = getdvar( "mapname" );

    if ( map != "zm_transit" && map != "zm_highrise" )
        return;

    clientscripts\mp\zombies\_zm_utility::include_powerup( "fire_sale" );
}

struct_class_init()
{
    level.struct_class_names = [];
    level.struct_class_names["target"] = [];
    level.struct_class_names["targetname"] = [];
    level.struct_class_names["script_noteworthy"] = [];
    level.struct_class_names["script_label"] = [];
    level.struct_class_names["classname"] = [];

    for ( i = 0; i < level.struct.size; i++ )
    {
        if ( isdefined( level.struct[i].targetname ) )
        {
            if ( !isdefined( level.struct_class_names["targetname"][level.struct[i].targetname] ) )
                level.struct_class_names["targetname"][level.struct[i].targetname] = [];

            size = level.struct_class_names["targetname"][level.struct[i].targetname].size;
            level.struct_class_names["targetname"][level.struct[i].targetname][size] = level.struct[i];
        }

        if ( isdefined( level.struct[i].target ) )
        {
            if ( !isdefined( level.struct_class_names["target"][level.struct[i].target] ) )
                level.struct_class_names["target"][level.struct[i].target] = [];

            size = level.struct_class_names["target"][level.struct[i].target].size;
            level.struct_class_names["target"][level.struct[i].target][size] = level.struct[i];
        }

        if ( isdefined( level.struct[i].script_noteworthy ) )
        {
            if ( !isdefined( level.struct_class_names["script_noteworthy"][level.struct[i].script_noteworthy] ) )
                level.struct_class_names["script_noteworthy"][level.struct[i].script_noteworthy] = [];

            size = level.struct_class_names["script_noteworthy"][level.struct[i].script_noteworthy].size;
            level.struct_class_names["script_noteworthy"][level.struct[i].script_noteworthy][size] = level.struct[i];
        }

        if ( isdefined( level.struct[i].script_label ) )
        {
            if ( !isdefined( level.struct_class_names["script_label"][level.struct[i].script_label] ) )
                level.struct_class_names["script_label"][level.struct[i].script_label] = [];

            size = level.struct_class_names["script_label"][level.struct[i].script_label].size;
            level.struct_class_names["script_label"][level.struct[i].script_label][size] = level.struct[i];
        }

        if ( isdefined( level.struct[i].classname ) )
        {
            if ( !isdefined( level.struct_class_names["classname"][level.struct[i].classname] ) )
                level.struct_class_names["classname"][level.struct[i].classname] = [];

            size = level.struct_class_names["classname"][level.struct[i].classname].size;
            level.struct_class_names["classname"][level.struct[i].classname][size] = level.struct[i];
        }
    }

    zmqol_enable_wallbuys();
    zmqol_add_semtex_wallbuy();
}

zmqol_semtex_wallbuy_origin()
{
    return ( getdvarintdefault( "zmqol_semtex_diner_x", -5176 ), getdvarintdefault( "zmqol_semtex_diner_y", -7925 ), getdvarintdefault( "zmqol_semtex_diner_z", -14 ) );
}

zmqol_client_add_struct( s_struct )
{
    if ( !isdefined( level.struct_class_names["targetname"][s_struct.targetname] ) )
        level.struct_class_names["targetname"][s_struct.targetname] = [];

    n_size = level.struct_class_names["targetname"][s_struct.targetname].size;
    level.struct_class_names["targetname"][s_struct.targetname][n_size] = s_struct;
}

zmqol_add_semtex_wallbuy()
{
    if ( getdvar( "mapname" ) != "zm_transit" || getdvar( "ui_zm_mapstartlocation" ) != "diner" )
        return;

    v_origin = zmqol_semtex_wallbuy_origin();
    v_angles = ( 0, getdvarintdefault( "zmqol_semtex_diner_yaw", 270 ), 0 );
    s_model = spawnstruct();
    s_model.targetname = "zmqol_semtex_diner";
    s_model.origin = v_origin;
    s_model.angles = v_angles;
    s_model.model = "semtex_bag";
    zmqol_client_add_struct( s_model );
    s_buy = spawnstruct();
    s_buy.targetname = "weapon_upgrade";
    s_buy.origin = v_origin;
    s_buy.angles = v_angles;
    s_buy.zombie_weapon_upgrade = "sticky_grenade_zm";
    s_buy.target = "zmqol_semtex_diner";
    zmqol_client_add_struct( s_buy );
    println( "[zm_qol] CLIENT diner semtex: wallbuy struct at (" + int( v_origin[0] ) + "," + int( v_origin[1] ) + "," + int( v_origin[2] ) + ")" );
}

zmqol_enable_wallbuys()
{
    str_map = getdvar( "mapname" );
    str_gametype = getdvar( "ui_gametype" );
    str_location = getdvar( "ui_zm_mapstartlocation" );
    a_origins = [];

    if ( str_map == "zm_transit" && str_location == "diner" )
    {
        a_origins[a_origins.size] = ( -5489, -7982.7, 62 );
        a_origins[a_origins.size] = ( -6399.2, -7938.5, 207.25 );
    }
    else if ( str_map == "zm_transit" && str_location == "tunnel" )
    {
        a_origins[a_origins.size] = ( -11839, -1695.1, 287 );
    }
    else if ( str_map == "zm_buried" && str_location == "street" && str_gametype == "zstandard" )
    {
        a_origins[a_origins.size] = ( -926.25, 510.5, 68 );
        a_origins[a_origins.size] = ( 609.5, 772.75, 54 );
        a_origins[a_origins.size] = ( 1.1, 1201.9, 68 );
    }
    else
        return;

    str_match = zmqol_wallbuy_match_string();
    a_targetnames = [];
    a_targetnames[a_targetnames.size] = "weapon_upgrade";
    a_targetnames[a_targetnames.size] = "bowie_upgrade";
    a_targetnames[a_targetnames.size] = "sickle_upgrade";
    a_targetnames[a_targetnames.size] = "tazer_upgrade";
    a_targetnames[a_targetnames.size] = "claymore_purchase";
    a_targetnames[a_targetnames.size] = "buildable_wallbuy";
    n_tagged = 0;

    foreach ( str_targetname in a_targetnames )
    {
        a_structs = getstructarray( str_targetname, "targetname" );

        if ( !isdefined( a_structs ) )
            continue;

        foreach ( s_struct in a_structs )
        {
            if ( !isdefined( s_struct.origin ) )
                continue;

            foreach ( v_origin in a_origins )
            {
                if ( distancesquared( s_struct.origin, v_origin ) > 256 )
                    continue;

                if ( isdefined( s_struct.script_noteworthy ) && s_struct.script_noteworthy != "" )
                {
                    s_struct.script_noteworthy = s_struct.script_noteworthy + "," + str_match;
                    n_tagged++;
                }

                break;
            }
        }
    }

    println( "[zm_qol] CLIENT enable_wallbuys - " + str_match + ": tagged " + n_tagged + " of " + a_origins.size + " requested" );
}

zmqol_wallbuy_match_string()
{
    str_gametype = getdvar( "ui_gametype" );
    str_location = getdvar( "ui_zm_mapstartlocation" );

    if ( ( str_location == "default" || str_location == "" ) && isdefined( level.default_start_location ) )
        str_location = level.default_start_location;

    if ( str_location == "" )
        return str_gametype;

    return str_gametype + "_" + str_location;
}

perks()
{
    if ( getdvar( "mapname" ) == "zm_transit" || getdvar( "mapname" ) == "zm_nuked" || getdvar( "mapname" ) == "zm_highrise" || getdvar( "mapname" ) == "zm_prison" || getdvar( "mapname" ) == "zm_buried" )
    {
        level.zombiemode_using_marathon_perk = 1;
        level.zombiemode_using_deadshot_perk = 1;
        level.zombiemode_using_additionalprimaryweapon_perk = 1;
        level.zombiemode_using_divetonuke_perk = 1;
        clientscripts\mp\zombies\_zm_perk_divetonuke::enable_divetonuke_perk_for_level();
        level.zombiemode_using_tombstone_perk = 1;
        level thread toggle_vending_deadshot_power_on_think();
        level thread toggle_vending_deadshot_power_off_think();
        level thread toggle_vending_divetonuke_power_on_think();
        level thread toggle_vending_divetonuke_power_off_think();
    }

    if ( getdvar( "mapname" ) == "zm_tomb" )
    {
        level.zombiemode_using_tombstone_perk = 1;
    }

    zmqol_enable_electric_cherry();
    zmqol_enable_vulture();
    zmqol_enable_whoswho();
    zmqol_enable_zombie_blood();
}

zmqol_zombie_blood_enabled()
{
    if ( getdvar( "mapname" ) == "zm_tomb" )
        return 0;

    if ( getdvar( "mapname" ) == "zm_prison" )
        return 0;

    return 1;
}

zmqol_enable_zombie_blood()
{
    if ( !zmqol_zombie_blood_enabled() )
        return;

    clientscripts\mp\zombies\_zm_utility::include_powerup( "zombie_blood" );
}

zmqol_zb_register()
{
    if ( !zmqol_zombie_blood_enabled() )
        return;

    onplayerconnect_callback( ::zmqol_zb_init_filter );
    level.vsmgr_filter_custom_enable["generic_filter_zombie_blood_b"] = ::zmqol_zb_vsmgr_enable_filter;
    registerclientfield( "allplayers", "player_zombie_blood_fx", 14000, 1, "int", ::zmqol_zb_toggle_fx, 0, 1 );
    level._effect["zombie_blood"] = loadfx( "maps/zombie_tomb/fx_tomb_pwr_up_zmb_blood" );
    level._effect["zombie_blood_1st"] = loadfx( "maps/zombie_tomb/fx_zm_blood_overlay_pclouds" );
    clientscripts\mp\zombies\_zm_powerups::add_zombie_powerup( "zombie_blood", "powerup_zombie_blood" );

    if ( isdefined( level.vsmgr ) && isdefined( level.vsmgr["visionset"] ) )
    {
        clientscripts\mp\_visionset_mgr::vsmgr_register_visionset_info( "zm_powerup_zombie_blood_visionset", 14000, 15, "zm_powerup_zombie_blood", "zm_powerup_zombie_blood" );
    }

    if ( isdefined( level.vsmgr ) && isdefined( level.vsmgr["overlay"] ) )
    {
        clientscripts\mp\_visionset_mgr::vsmgr_register_overlay_info_style_filter( "zm_powerup_zombie_blood_overlay", 14000, 15, 1, 0, "generic_filter_zombie_blood_b" );
    }
}

zmqol_zb_vsmgr_enable_filter( curr_info )
{
    zmqol_zb_enable_filter( self, curr_info.filter_index, 0.0 );
}

zmqol_zb_init_filter( localclientnum )
{
    player = getlocalplayer( localclientnum );
    clientscripts\mp\_filter::init_filter_indices();
    clientscripts\mp\_filter::map_material_helper( player, "generic_filter_zombie_blood_b" );
}

zmqol_zb_set_overlay_amount( player, filterid, amount )
{
    player set_filter_pass_constant( filterid, 0, 0, amount );
}

zmqol_zb_enable_filter( player, filterid, zombie_blood_warp_shift_enabled )
{
    player set_filter_pass_material( filterid, 0, level.filter_matid["generic_filter_zombie_blood_b"] );
    player set_filter_pass_enabled( filterid, 0, 1 );
    self thread zmqol_zb_overlay_fade_in();
}

zmqol_zb_overlay_fade_in()
{
    self endon( "entity_shutdown" );
    zmqol_zb_overlay_lerp( 1.0, 0.2, 0.3 );
    wait 0.2;
    zmqol_zb_overlay_lerp( 0.2, 0.8, 1.0 );
}

zmqol_zb_overlay_lerp( n_fraction_start, n_fraction_end, n_trans_time )
{
    n_fraction_delta = n_fraction_end - n_fraction_start;
    zmqol_zb_set_overlay_amount( self, 1, n_fraction_start );

    for ( n_time = 0.0; n_time < n_trans_time; n_time = n_time + 0.0166667 )
    {
        n_fraction = n_fraction_start + n_fraction_delta * n_time / n_trans_time;
        zmqol_zb_set_overlay_amount( self, 1, n_fraction );
        wait 0.0166667;
    }

    zmqol_zb_set_overlay_amount( self, 1, n_fraction_end );
}

zmqol_zb_toggle_fx( localclientnum, oldval, newval, bnewent, binitialsnap, fieldname, bwasdemojump )
{
    if ( isspectating( localclientnum, 0 ) || isdemoplaying() )
        return;

    if ( newval == 1 )
    {
        if ( self islocalplayer() && self getlocalclientnumber() == localclientnum )
        {
            if ( !isdefined( self.zombie_blood_fx ) )
            {
                self.zombie_blood_fx = playviewmodelfx( localclientnum, level._effect["zombie_blood_1st"], "tag_camera" );
                playsound( localclientnum, "zmqol_zombieblood_start", ( 0, 0, 0 ) );
                playloopat( "zmqol_zombieblood_loop", ( 0, 0, 0 ) );
            }
        }
    }
    else if ( isdefined( self.zombie_blood_fx ) )
    {
        stopfx( localclientnum, self.zombie_blood_fx );
        playsound( localclientnum, "zmqol_zombieblood_stop", ( 0, 0, 0 ) );
        stoploopat( "zmqol_zombieblood_loop", ( 0, 0, 0 ) );
        self.zombie_blood_fx = undefined;
    }
}

zmqol_whoswho_enabled()
{
    map = getdvar( "mapname" );

    if ( map == "zm_highrise" )
        return 0;

    if ( map == "zm_prison" )
        return 0;

    if ( map == "zm_buried" )
        return 0;

    return 1;
}

zmqol_whoswho_clone_glow_enabled()
{
    if ( !zmqol_whoswho_enabled() )
        return 0;

    return getdvar( "mapname" ) == "zm_transit";
}

zmqol_enable_whoswho()
{
    if ( !zmqol_whoswho_enabled() )
        return;

    level.zombiemode_using_chugabud_perk = 1;
    registerclientfield( "actor", "clientfield_whos_who_clone_glow_shader", 5000, 1, "int", clientscripts\mp\zombies\_zm_perks::chugabud_whos_who_shader, 0 );

    if ( zmqol_whoswho_clone_glow_enabled() )
        registerclientfield( "scriptmover", "zmqol_whoswho_clone_glow", 5000, 1, "int", clientscripts\mp\zombies\_zm_perks::chugabud_whos_who_shader, 0 );

    registerclientfield( "toplayer", "clientfield_whos_who_audio", 5000, 1, "int", ::zmqol_whoswho_audio, 0 );
    registerclientfield( "toplayer", "clientfield_whos_who_filter", 5000, 1, "int", ::zmqol_whoswho_filter, 0 );
    level thread clientscripts\mp\zombies\_zm_perks::chugabud_setup_afterlife_filters();
}

zmqol_whoswho_filter( localclientnum, oldval, newval, bnewent, binitialsnap, fieldname, bwasdemojump )
{
    player = getlocalplayers()[localclientnum];

    if ( !isdefined( player ) )
        return;

    if ( newval == 1 )
    {
        if ( !isdefined( level.zmqol_whoswho_saved_vision ) )
            level.zmqol_whoswho_saved_vision = [];

        level.zmqol_whoswho_saved_vision[localclientnum] = getvisionsetnaked( localclientnum );
        visionsetnaked( localclientnum, "zm_whos_who", 0.5 );
        println( "[zm_qol] CLIENT whoswho: vision -> zm_whos_who (was '" + level.zmqol_whoswho_saved_vision[localclientnum] + "')" );
        clientscripts\mp\zombies\_zm_perks::enable_filter_afterlife( player, 5 );
    }
    else
    {
        clientscripts\mp\zombies\_zm_perks::disable_filter_afterlife( player, 5 );
        str_restore = undefined;

        if ( isdefined( level.zmqol_whoswho_saved_vision ) )
            str_restore = level.zmqol_whoswho_saved_vision[localclientnum];

        if ( !isdefined( str_restore ) || str_restore == "" || str_restore == "undefined" )
            str_restore = getdvar( "mapname" );

        visionsetnaked( localclientnum, str_restore, 0.5 );
        println( "[zm_qol] CLIENT whoswho: filter OFF, vision -> '" + str_restore + "'" );
    }
}

zmqol_whoswho_visionset_probe()
{
    wait 1;

    if ( !isdefined( level.vsmgr ) || !isdefined( level.vsmgr["visionset"] ) )
    {
        println( "[zm_qol] CLIENT whoswho visionset: no manager" );
        return;
    }

    if ( !isdefined( level.vsmgr["visionset"].info["zm_whos_who"] ) )
    {
        println( "[zm_qol] CLIENT whoswho visionset: NOT REGISTERED - total visionsets " + level.vsmgr["visionset"].info.size );
        return;
    }

    str_slot = "UNASSIGNED";

    if ( isdefined( level.vsmgr["visionset"].info["zm_whos_who"].slot_index ) )
        str_slot = "" + level.vsmgr["visionset"].info["zm_whos_who"].slot_index;

    println( "[zm_qol] CLIENT whoswho visionset: registered, slot_index " + str_slot + ", total visionsets " + level.vsmgr["visionset"].info.size );
}

zmqol_whoswho_audio( localclientnum, oldval, newval, bnewent, binitialsnap, fieldname, bwasdemojump )
{
    if ( newval == 1 )
    {
        if ( !isdefined( level.zmqol_ww_sndent ) )
            level.zmqol_ww_sndent = spawn( localclientnum, ( 0, 0, 0 ), "script_origin" );

        playsound( localclientnum, "zmqol_ww_activate", ( 0, 0, 0 ) );
        level.zmqol_ww_sndent playloopsound( "zmqol_ww_looper", 3 );
    }
    else
    {
        if ( isdefined( level.zmqol_ww_sndent ) )
        {
            level.zmqol_ww_sndent stoploopsound( 1 );
            level.zmqol_ww_sndent delete();
            level.zmqol_ww_sndent = undefined;
        }
    }
}

zmqol_vulture_enabled()
{
    map = getdvar( "mapname" );

    if ( !getdvarintdefault( "zmqol_vulture", 1 ) )
        return 0;

    if ( map == "zm_buried" )
        return 0;

    if ( map == "zm_tomb" )
        return 0;

    str_gametype = getdvar( "ui_gametype" );

    if ( map == "zm_transit" && getdvar( "ui_zm_mapstartlocation" ) == "transit" && str_gametype != "zstandard" && str_gametype != "zgrief" )
        return 0;

    return 1;
}

zmqol_vulture_has_actor_field()
{
    return getdvar( "mapname" ) != "zm_tomb";
}

zmqol_vulture_has_disease_meter()
{
    return getdvar( "mapname" ) != "zm_prison";
}

zmqol_vulture_has_scriptmover_field()
{
    return getdvar( "mapname" ) != "zm_tomb";
}

zmqol_init_vulture_trimmed()
{
    registerclientfield( "toplayer", "vulture_perk_toplayer", 12000, 1, "int", clientscripts\mp\zombies\_zm_perk_vulture::vulture_callback_toplayer, 0, 1 );

    if ( zmqol_vulture_has_actor_field() )
        registerclientfield( "actor", "vulture_perk_actor", 12000, 2, "int", clientscripts\mp\zombies\_zm_perk_vulture::vulture_callback_actor, 0, 0 );

    if ( zmqol_vulture_has_scriptmover_field() )
        registerclientfield( "scriptmover", "vulture_perk_scriptmover", 12000, 4, "int", clientscripts\mp\zombies\_zm_perk_vulture::vulture_callback_scriptmover, 0, 0 );

    registerclientfield( "zbarrier", "vulture_perk_zbarrier", 12000, 1, "int", clientscripts\mp\zombies\_zm_perk_vulture::vulture_vision_mystery_box, 0, 0 );
    registerclientfield( "toplayer", "sndVultureStink", 12000, 1, "int", clientscripts\mp\zombies\_zm_perk_vulture::sndvulturestink );
    registerclientfield( "world", "vulture_perk_disable_solo_quick_revive_glow", 12000, 1, "int", clientscripts\mp\zombies\_zm_perk_vulture::vulture_disable_solo_quick_revive_glow, 0, 0 );

    if ( zmqol_vulture_has_disease_meter() )
    {
        registerclientfield( "toplayer", "vulture_perk_disease_meter", 12000, 5, "float", clientscripts\mp\zombies\_zm_perk_vulture::vulture_callback_stink_active, 0, 1 );
        setupclientfieldcodecallbacks( "toplayer", 1, "vulture_perk_disease_meter" );
    }

    clientscripts\mp\_visionset_mgr::vsmgr_register_overlay_info_style_filter( "vulture_stink_overlay", 12000, 31, 0, 0, "generic_filter_zombie_perk_vulture", 0 );
    level._effect["vulture_perk_zombie_stink"] = loadfx( "maps/zombie/fx_zm_vulture_perk_stink" );
    level._effect["vulture_perk_zombie_stink_trail"] = loadfx( "maps/zombie/fx_zm_vulture_perk_stink_trail" );
    level._effect["vulture_perk_bonus_drop"] = loadfx( "misc/fx_zombie_powerup_vulture" );
    level._effect["vulture_drop_picked_up"] = loadfx( "misc/fx_zombie_powerup_grab" );
    level._effect["vulture_perk_wallbuy_static"] = loadfx( "maps/zombie/fx_zm_vulture_wallbuy_rifle" );
    level._effect["vulture_perk_wallbuy_dynamic"] = loadfx( "maps/zombie/fx_zm_vulture_glow_question" );
    level._effect["vulture_perk_machine_glow_doubletap"] = loadfx( "maps/zombie/fx_zm_vulture_glow_dbltap" );
    level._effect["vulture_perk_machine_glow_juggernog"] = loadfx( "maps/zombie/fx_zm_vulture_glow_jugg" );
    level._effect["vulture_perk_machine_glow_revive"] = loadfx( "maps/zombie/fx_zm_vulture_glow_revive" );
    level._effect["vulture_perk_machine_glow_speed"] = loadfx( "maps/zombie/fx_zm_vulture_glow_speed" );
    level._effect["vulture_perk_machine_glow_marathon"] = loadfx( "maps/zombie/fx_zm_vulture_glow_marathon" );
    level._effect["vulture_perk_machine_glow_mule_kick"] = loadfx( "maps/zombie/fx_zm_vulture_glow_mule" );
    level._effect["vulture_perk_machine_glow_pack_a_punch"] = loadfx( "maps/zombie/fx_zm_vulture_glow_pap" );
    level._effect["vulture_perk_machine_glow_vulture"] = loadfx( "maps/zombie/fx_zm_vulture_glow_vulture" );
    level._effect["vulture_perk_mystery_box_glow"] = loadfx( "maps/zombie/fx_zm_vulture_glow_mystery_box" );
    level._effect["vulture_perk_powerup_drop"] = loadfx( "maps/zombie/fx_zm_vulture_glow_powerup" );
    level._effect["vulture_perk_zombie_eye_glow"] = loadfx( "misc/fx_zombie_eye_vulture" );
    level.perk_vulture = spawnstruct();
    level.perk_vulture.array_stink_zombies = [];
    level.perk_vulture.array_stink_drop_locations = [];
    level.perk_vulture.players_with_vulture_perk = [];
    level.perk_vulture.vulture_vision_fx_list = [];
    level.perk_vulture.clientfields = spawnstruct();
    level.perk_vulture.clientfields.scriptmovers = [];
    level.perk_vulture.clientfields.scriptmovers[0] = clientscripts\mp\zombies\_zm_perk_vulture::vulture_stink_fx;
    level.perk_vulture.clientfields.scriptmovers[1] = clientscripts\mp\zombies\_zm_perk_vulture::vulture_drop_fx;
    level.perk_vulture.clientfields.scriptmovers[2] = clientscripts\mp\zombies\_zm_perk_vulture::vulture_drop_pickup;
    level.perk_vulture.clientfields.scriptmovers[3] = clientscripts\mp\zombies\_zm_perk_vulture::vulture_powerup_drop;
    level.perk_vulture.clientfields.actors = [];
    level.perk_vulture.clientfields.actors[1] = clientscripts\mp\zombies\_zm_perk_vulture::vulture_eye_glow;
    level.perk_vulture.clientfields.actors[0] = clientscripts\mp\zombies\_zm_perk_vulture::vulture_stink_trail_fx;
    level.perk_vulture.clientfields.toplayer = [];
    level.perk_vulture.clientfields.toplayer[0] = clientscripts\mp\zombies\_zm_perk_vulture::vulture_toggle;
    level.perk_vulture.disable_solo_quick_revive_glow = 0;
    level.perk_vulture.custom_funcs_enable = [];
    level.perk_vulture.custom_funcs_disable = [];
    level.perk_vulture.custom_funcs_enable[0] = ::zmqol_vulture_machines_enable;
    level.perk_vulture.custom_funcs_disable[0] = ::zmqol_vulture_machines_disable;
    level.zombie_eyes_clientfield_cb_additional = clientscripts\mp\zombies\_zm_perk_vulture::vulture_eye_glow_callback_from_system;
}

zmqol_vulture_perks_match_string()
{
    str_gametype = getdvar( "ui_gametype" );
    str_location = getdvar( "ui_zm_mapstartlocation" );

    if ( ( str_location == "default" || str_location == "" ) && isdefined( level.default_start_location ) )
        str_location = level.default_start_location;

    if ( !isdefined( str_location ) || str_location == "" || str_gametype == "" )
        return "";

    return str_gametype + "_perks_" + str_location;
}

zmqol_vulture_machines_build()
{
    a_out = [];
    a_structs = getstructarray( "zm_perk_machine", "targetname" );

    if ( !isdefined( a_structs ) || a_structs.size < 1 )
        return a_out;

    str_match = zmqol_vulture_perks_match_string();

    for ( i = 0; i < a_structs.size; i++ )
    {
        s_spot = a_structs[i];

        if ( !isdefined( s_spot.origin ) || !isdefined( s_spot.script_noteworthy ) )
            continue;

        if ( isdefined( s_spot.script_string ) )
        {
            if ( str_match == "" )
                continue;

            b_match = 0;
            a_tokens = strtok( s_spot.script_string, " " );

            for ( t = 0; t < a_tokens.size; t++ )
            {
                if ( a_tokens[t] == str_match )
                    b_match = 1;
            }

            if ( !b_match )
                continue;
        }

        a_out[a_out.size] = s_spot;
    }

    println( "[zm_qol] CLIENT vulture machines: " + a_out.size + " of " + a_structs.size + " structs match '" + str_match + "'" );
    return a_out;
}

zmqol_vulture_machine_fx( str_perk )
{
    switch ( str_perk )
    {
        case "specialty_armorvest":
            return "vulture_perk_machine_glow_juggernog";
        case "specialty_rof":
            return "vulture_perk_machine_glow_doubletap";
        case "specialty_quickrevive":
            return "vulture_perk_machine_glow_revive";
        case "specialty_fastreload":
            return "vulture_perk_machine_glow_speed";
        case "specialty_weapupgrade":
            return "vulture_perk_machine_glow_pack_a_punch";
        case "specialty_longersprint":
            return "vulture_perk_machine_glow_marathon";
        case "specialty_additionalprimaryweapon":
            return "vulture_perk_machine_glow_mule_kick";
        case "specialty_nomotionsensor":
            return "vulture_perk_machine_glow_vulture";
    }

    return "vulture_perk_wallbuy_dynamic";
}

zmqol_vulture_machine_should_show( localclientnumber, str_perk )
{
    if ( str_perk == "specialty_quickrevive" && isdefined( level.perk_vulture.disable_solo_quick_revive_glow ) && level.perk_vulture.disable_solo_quick_revive_glow )
        return 0;

    if ( str_perk == "specialty_weapupgrade" || str_perk == "specialty_nomotionsensor" )
        return 1;

    return !( self hasperk( localclientnumber, str_perk ) );
}

zmqol_vulture_machines_enable( localclientnumber )
{
    if ( !isdefined( level.zmqol_vulture_machines ) )
        level.zmqol_vulture_machines = zmqol_vulture_machines_build();

    self zmqol_vulture_machines_disable( localclientnumber );
    a_ids = [];
    a_perks = [];

    for ( i = 0; i < level.zmqol_vulture_machines.size; i++ )
    {
        s_spot = level.zmqol_vulture_machines[i];
        str_perk = s_spot.script_noteworthy;

        if ( !( self zmqol_vulture_machine_should_show( localclientnumber, str_perk ) ) )
            continue;

        str_fx = zmqol_vulture_machine_fx( str_perk );

        if ( !isdefined( level._effect[str_fx] ) )
            continue;

        v_angles = ( 0, 0, 0 );

        if ( isdefined( s_spot.angles ) )
            v_angles = s_spot.angles;

        a_ids[a_ids.size] = playfx( localclientnumber, level._effect[str_fx], s_spot.origin, anglestoforward( v_angles ), anglestoup( v_angles ) );
        a_perks[a_perks.size] = str_perk;
    }

    if ( !isdefined( level.zmqol_vulture_fx ) )
        level.zmqol_vulture_fx = [];

    level.zmqol_vulture_fx[localclientnumber] = spawnstruct();
    level.zmqol_vulture_fx[localclientnumber].ids = a_ids;
    level.zmqol_vulture_fx[localclientnumber].perks = a_perks;
}

zmqol_vulture_machines_disable( localclientnumber )
{
    if ( !isdefined( level.zmqol_vulture_fx ) || !isdefined( level.zmqol_vulture_fx[localclientnumber] ) )
        return;

    s_fx = level.zmqol_vulture_fx[localclientnumber];

    for ( i = 0; i < s_fx.ids.size; i++ )
    {
        if ( isdefined( s_fx.ids[i] ) )
            deletefx( localclientnumber, s_fx.ids[i], 1 );
    }

    level.zmqol_vulture_fx[localclientnumber] = undefined;
}

zmqol_vulture_global_perk_callback( localclientnumber, oldval, newval, bnewent, binitialsnap, fieldname, bwasdemojump )
{
    self clientscripts\mp\zombies\_zm_perk_vulture::vulture_global_perk_client_callback( localclientnumber, oldval, newval, bnewent, binitialsnap, fieldname, bwasdemojump );

    if ( !isdefined( level.perk_vulture ) || !( newval & 1 ) )
        return;

    if ( !isdefined( level.zmqol_vulture_fx ) || !isdefined( level.zmqol_vulture_fx[localclientnumber] ) )
        return;

    if ( !isdefined( level.perk_vulture.vulture_vision ) || !isdefined( level.perk_vulture.vulture_vision.perk_clientfields ) )
        return;

    if ( !isdefined( level.perk_vulture.vulture_vision.perk_clientfields[fieldname] ) )
        return;

    str_perk = level.perk_vulture.vulture_vision.perk_clientfields[fieldname];

    if ( self zmqol_vulture_machine_should_show( localclientnumber, str_perk ) )
        return;

    s_fx = level.zmqol_vulture_fx[localclientnumber];

    for ( i = 0; i < s_fx.perks.size; i++ )
    {
        if ( s_fx.perks[i] != str_perk || !isdefined( s_fx.ids[i] ) )
            continue;

        deletefx( localclientnumber, s_fx.ids[i], 1 );
        s_fx.ids[i] = undefined;
    }
}

zmqol_vulture_after_connect( localclientnumber )
{
    if ( isdefined( level.perk_vulture ) && isdefined( level.perk_vulture.vulture_vision ) )
        level.perk_vulture.vulture_vision.perk_machines = [];
}

zmqol_enable_vulture()
{
    if ( !zmqol_vulture_enabled() )
        return;

    if ( isdefined( level._custom_perks ) && isdefined( level._custom_perks["specialty_nomotionsensor"] ) )
        return;

    clientscripts\mp\zombies\_zm_perk_vulture::enable_vulture_perk_for_level();
    level._custom_perks["specialty_nomotionsensor"].init_thread = ::zmqol_init_vulture_trimmed;
    onplayerconnect_callback( ::zmqol_vulture_after_connect );
    level.zombies_global_perk_client_callback = ::zmqol_vulture_global_perk_callback;
}

zmqol_enable_electric_cherry()
{
    map = getdvar( "mapname" );

    if ( map != "zm_transit" && map != "zm_nuked" && map != "zm_highrise" && map != "zm_buried" )
        return;

    if ( isdefined( level._custom_perks ) && isdefined( level._custom_perks["specialty_grenadepulldeath"] ) )
        return;

    clientscripts\mp\zombies\_zm_perk_electric_cherry::enable_electric_cherry_perk_for_level();
}

toggle_vending_deadshot_power_on_think()
{
    while ( 1 )
    {
        level waittill( "toggle_vending_deadshot_power_on" );
        ents = getentarray( 0 );

        foreach ( ent in ents )
        {
            if ( isdefined( ent.model ) && ent.model == "p6_zm_al_vending_ads_on" )
            {
                ent mapshaderconstant( 0, 1, "ScriptVector0" );
                ent setshaderconstant( 0, 1, 0, 0.5, 0, 0 );
            }
        }
    }
}

toggle_vending_deadshot_power_off_think()
{
    while ( 1 )
    {
        level waittill( "toggle_vending_deadshot_power_off" );
        ents = getentarray( 0 );

        foreach ( ent in ents )
        {
            if ( isdefined( ent.model ) && ent.model == "p6_zm_al_vending_ads_on" )
            {
                ent mapshaderconstant( 0, 1, "ScriptVector0" );
                ent setshaderconstant( 0, 1, 0, 0, 0, 0 );
            }
        }
    }
}

toggle_vending_divetonuke_power_on_think()
{
    while ( 1 )
    {
        level waittill( "toggle_vending_divetonuke_power_on" );
        ents = getentarray( 0 );

        foreach ( ent in ents )
        {
            if ( isdefined( ent.model ) && ent.model == "p6_zm_al_vending_nuke_on" )
            {
                ent mapshaderconstant( 0, 1, "ScriptVector0" );
                ent setshaderconstant( 0, 1, 0, 0.5, 0, 0 );
            }
        }
    }
}

toggle_vending_divetonuke_power_off_think()
{
    while ( 1 )
    {
        level waittill( "toggle_vending_divetonuke_power_off" );
        ents = getentarray( 0 );

        foreach ( ent in ents )
        {
            if ( isdefined( ent.model ) && ent.model == "p6_zm_al_vending_nuke_on" )
            {
                ent mapshaderconstant( 0, 1, "ScriptVector0" );
                ent setshaderconstant( 0, 1, 0, 0, 0, 0 );
            }
        }
    }
}

perks_register_clientfield()
{
    bits = 1;

    if ( clientscripts\mp\zombies\_zm_weapons::is_weapon_included( "emp_grenade_zm" ) )
    {
        bits = 2;
    }

    if ( is_true( level.zombiemode_using_additionalprimaryweapon_perk ) )
    {
        registerclientfield( "toplayer", "perk_additional_primary_weapon", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_deadshot_perk ) )
    {
        registerclientfield( "toplayer", "perk_dead_shot", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_doubletap_perk ) )
    {
        registerclientfield( "toplayer", "perk_double_tap", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_juggernaut_perk ) )
    {
        registerclientfield( "toplayer", "perk_juggernaut", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_marathon_perk ) )
    {
        registerclientfield( "toplayer", "perk_marathon", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_revive_perk ) )
    {
        registerclientfield( "toplayer", "perk_quick_revive", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_sleightofhand_perk ) )
    {
        registerclientfield( "toplayer", "perk_sleight_of_hand", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_tombstone_perk ) )
    {
        registerclientfield( "toplayer", "perk_tombstone", 1, bits, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( is_true( level.zombiemode_using_perk_intro_fx ) )
    {
        registerclientfield( "scriptmover", "clientfield_perk_intro_fx", 1000, 1, "int", ::perk_meteor_fx, 0 );
    }

    if ( is_true( level.zombiemode_using_chugabud_perk ) )
    {
        registerclientfield( "toplayer", "perk_chugabud", 1000, 1, "int", level.zombies_global_perk_client_callback, 0, 1 );
    }

    if ( level._custom_perks.size > 0 )
    {
        a_keys = getarraykeys( level._custom_perks );

        for ( i = 0; i < a_keys.size; i++ )
        {
            if ( isdefined( level._custom_perks[a_keys[i]].clientfield_register ) )
            {
                level [[ level._custom_perks[a_keys[i]].clientfield_register ]]();
            }
        }
    }

    if ( zmqol_whoswho_enabled() && isdefined( level.vsmgr ) && isdefined( level.vsmgr["visionset"] ) )
    {
        clientscripts\mp\_visionset_mgr::vsmgr_register_visionset_info( "zm_whos_who", 5000, 1, "zm_whos_who", "zm_whos_who" );
        level thread zmqol_whoswho_visionset_probe();
    }

    zmqol_zb_register();
    level thread perk_init_code_callbacks();
}

init_client_flag_callback_funcs()
{
    level.disable_deadshot_clientfield = 1;
    level._client_flag_callbacks = [];
    level._client_flag_callbacks["vehicle"] = [];
    level._client_flag_callbacks["player"] = [];
    level._client_flag_callbacks["actor"] = [];
    level._client_flag_callbacks["scriptmover"] = [];

    if ( isdefined( level.use_clientside_board_fx ) && level.use_clientside_board_fx )
    {
        register_clientflag_callback( "scriptmover", level._zombie_scriptmover_flag_board_vertical_fx, ::handle_vertical_board_clientside_fx );
        register_clientflag_callback( "scriptmover", level._zombie_scriptmover_flag_board_horizontal_fx, ::handle_horizontal_board_clientside_fx );
    }

    if ( isdefined( level.use_clientside_rock_tearin_fx ) && level.use_clientside_rock_tearin_fx )
    {
        register_clientflag_callback( "scriptmover", level._zombie_scriptmover_flag_rock_fx, ::handle_rock_clientside_fx );
    }

    register_clientflag_callback( "scriptmover", level._zombie_scriptmover_flag_box_random, clientscripts\mp\zombies\_zm_weapons::weapon_box_callback );

    if ( !is_true( level.disable_deadshot_clientfield ) )
    {
        registerclientfield( "toplayer", "deadshot_perk", 1, 1, "int", ::player_deadshot_perk_handler, 0, 1 );
    }

    if ( !is_true( level._no_navcards ) )
    {
        if ( level.scr_zm_ui_gametype == "zclassic" && !level.createfx_enabled )
        {
            registerclientfield( "allplayers", "navcard_held", 1, 4, "int", undefined, 0, 1 );
            level thread set_clientfield_navcard_code_callback( "navcard_held" );
        }
    }

    if ( !is_true( level._no_water_risers ) )
    {
        registerclientfield( "actor", "zombie_riser_fx_water", 1, 1, "int", ::handle_zombie_risers_water, 1 );
    }

    if ( is_true( level._foliage_risers ) )
    {
        registerclientfield( "actor", "zombie_riser_fx_foliage", 12000, 1, "int", ::handle_zombie_risers_foliage, 1 );
    }

    registerclientfield( "actor", "zombie_riser_fx", 1, 1, "int", ::zmqol_handle_zombie_risers, 1 );

    if ( is_true( level.risers_use_low_gravity_fx ) )
    {
        registerclientfield( "actor", "zombie_riser_fx_lowg", 1, 1, "int", ::handle_zombie_risers_lowg, 1 );
    }
}

zmqol_handle_zombie_risers( localclientnum, oldval, newval, bnewent, binitialsnap, fieldname, bwasdemojump )
{
    if ( !oldval && newval )
    {
        if ( !isdefined( level.zmqol_riser_logged ) )
        {
            level.zmqol_riser_logged = 1;
            str_org = "UNDEFINED";
            str_ply = "UNDEFINED";
            str_dist = "n/a";
            player = getlocalplayer( localclientnum );

            if ( isdefined( self.origin ) )
                str_org = "" + self.origin;

            if ( isdefined( player ) && isdefined( player.origin ) )
            {
                str_ply = "" + player.origin;

                if ( isdefined( self.origin ) )
                    str_dist = "" + int( distance( self.origin, player.origin ) );
            }

            println( "[zm_qol] RISER PROBE  riser=" + str_org + "  player=" + str_ply + "  dist=" + str_dist + "  (alias goes silent past ~1000)" + "  bnewent=" + bnewent + "  binitialsnap=" + binitialsnap );
        }

        str_snd = "zmqol_zombie_riser";

        if ( isdefined( level.riser_type ) && level.riser_type == "snow" )
            str_snd = "zmb_zombie_spawn_snow";

        playsound( 0, str_snd, self.origin );
    }

    self clientscripts\mp\zombies\_zm::handle_zombie_risers( localclientnum, oldval, newval, bnewent, binitialsnap, fieldname, bwasdemojump );
}

zmqol_testsound_watch()
{
    str_last = "";

    for (;;)
    {
        wait 0.25;
        str_now = getdvar( "zmqol_testsound" );

        if ( !isdefined( str_now ) || str_now == "" || str_now == str_last )
            continue;

        str_last = str_now;
        tokens = strtok( str_now, " " );

        if ( !isdefined( tokens ) || tokens.size == 0 )
            continue;

        str_alias = tokens[0];
        player = getlocalplayer( 0 );

        if ( !isdefined( player ) || !isdefined( player.origin ) )
        {
            println( "[zm_qol] TESTSOUND: no local player yet, ignored" );
            continue;
        }

        println( "[zm_qol] TESTSOUND 1/3  2D       '" + str_alias + "'" );
        playsound( 0, str_alias );
        wait 1.2;
        player = getlocalplayer( 0 );

        if ( !isdefined( player ) || !isdefined( player.origin ) )
            continue;

        println( "[zm_qol] TESTSOUND 2/3  3D@you   '" + str_alias + "'" );
        playsound( 0, str_alias, player.origin );
        wait 1.2;
        player = getlocalplayer( 0 );

        if ( !isdefined( player ) || !isdefined( player.origin ) )
            continue;

        println( "[zm_qol] TESTSOUND 3/3  CONTROL  'zmb_powerup_grabbed'" );
        playsound( 0, "zmb_powerup_grabbed", player.origin );
    }
}
