// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;
#include maps\mp\zombies\_zm_weapons;
#include maps\mp\zombies\_zm_weapon_locker;
#include maps\mp\zm_tomb;
#include maps\mp\zm_tomb_utility;

main()
{
    replacefunc( maps\mp\zm_tomb_dig::swap_weapon, ::custom_swap_weapon );
    replacefunc( maps\mp\zm_tomb_ee_side::check_for_change, ::origins_change_patch );
    replacefunc( maps\mp\zm_tomb_utility::check_solo_status, ::qol_check_solo_status );
    replacefunc( maps\mp\zombies\_zm_perk_random::init_machines, ::zmqol_tomb_no_native_wunderfizz );
    replacefunc( maps\mp\zombies\_zm_perk_random::start_random_machine, ::zmqol_tomb_no_native_wunderfizz );
    level thread zmqol_mp40_keep_wallbuys_stalker();
    zmqol_register_survival_clientfields();
}

zmqol_register_survival_clientfields()
{
    if ( is_classic() )
        return;

    registerclientfield( "toplayer", "sndMudSlow", 14000, 1, "int" );
    registerclientfield( "scriptmover", "element_glow_fx", 14000, 4, "int", undefined, 0 );
    registerclientfield( "scriptmover", "bryce_cake", 14000, 2, "int", undefined, 0 );
    registerclientfield( "scriptmover", "switch_spark", 14000, 1, "int", undefined, 0 );
    registerclientfield( "allplayers", "electric_cherry_reload_fx", 9000, 2, "int" );
}

zmqol_register_survival_visionset()
{
    if ( is_classic() )
        return;

    if ( !isdefined( level.vsmgr ) || !isdefined( level.vsmgr["visionset"] ) )
        return;

    maps\mp\_visionset_mgr::vsmgr_register_info( "visionset", "zm_perk_divetonuke", 9000, 400, 5, 1 );
}

init()
{
    level thread zmqol_hide_native_wunderfizz();
    level thread zmqol_probe_capture_zones();
    level thread zmqol_capture_objectives_fix();
    level thread zmqol_capture_hud_nudge();
    zmqol_register_survival_visionset();
    level thread zmqol_power_up_all_generators();
    level thread zmqol_disable_staff_relay_switches();
    level thread zmqol_remove_survival_ee_props();
    level thread zmqol_open_stock_barriers();
    level thread zmqol_wunderfizz_all_perks();
    added_weapons();
    level.zmqol_boss_name = "panzer";
    level.zmqol_boss_spawn_func = ::zmqol_spawn_panzer;
}

zmqol_spawn_panzer( n_amount )
{
    if ( !isdefined( level.mechz_spawners ) || !isdefined( level.mechz_left_to_spawn ) )
        return 0;

    level.mechz_left_to_spawn += n_amount;
    level notify( "spawn_mechz" );
    return n_amount;
}

zmqol_wunderfizz_all_perks()
{
    level waittill( "start_of_round" );
    wait 0.05;
    a_perks = scripts\zm\wunderfizz::getperks();

    if ( !isdefined( a_perks ) || a_perks.size < 1 )
        return;

    if ( !isdefined( level._random_perk_machine_perk_list ) )
        level._random_perk_machine_perk_list = [];

    n_added = 0;

    for ( i = 0; i < a_perks.size; i++ )
    {
        str_perk = a_perks[i];

        if ( !isdefined( level._custom_perks ) || !isdefined( level._custom_perks[str_perk] ) || !isdefined( level._custom_perks[str_perk].player_thread_give ) )
        {
            if ( !zmqol_tomb_perk_is_stock( str_perk ) )
                continue;
        }

        if ( isinarray( level._random_perk_machine_perk_list, str_perk ) )
            continue;

        maps\mp\zombies\_zm_perk_random::include_perk_in_random_rotation( str_perk );
        n_added++;
    }

    println( "[zm_qol] origins: added " + n_added + " perk(s) to the native Wunderfizz rotation, list is now " + level._random_perk_machine_perk_list.size );

    if ( isdefined( level.custom_random_perk_weights ) && !isdefined( level.zmqol_tomb_weights_prev ) )
    {
        level.zmqol_tomb_weights_prev = level.custom_random_perk_weights;
        level.custom_random_perk_weights = ::zmqol_tomb_perk_weights;
    }
}

zmqol_tomb_perk_weights()
{
    a_keys = self [[ level.zmqol_tomb_weights_prev ]]();

    if ( !isdefined( a_keys ) || a_keys.size < 1 )
        return a_keys;

    a_want = [];
    a_have = [];

    for ( i = 0; i < a_keys.size; i++ )
    {
        str_perk = level._random_perk_machine_perk_list[a_keys[i]];

        if ( !isdefined( str_perk ) )
            continue;

        if ( self hasperk( str_perk ) )
            a_have[a_have.size] = a_keys[i];
        else
            a_want[a_want.size] = a_keys[i];
    }

    for ( i = 0; i < a_have.size; i++ )
        a_want[a_want.size] = a_have[i];

    return a_want;
}

zmqol_tomb_perk_is_stock( str_perk )
{
    a_stock = array( "specialty_armorvest", "specialty_quickrevive", "specialty_fastreload", "specialty_rof", "specialty_longersprint", "specialty_additionalprimaryweapon", "specialty_deadshot", "specialty_flakjacket", "specialty_scavenger" );
    return isinarray( a_stock, str_perk );
}

zmqol_capture_objectives_fix()
{
    level endon( "end_game" );

    if ( !is_classic() )
        return;

    level thread zmqol_capture_objectives_on_connect();
    n_pass = 0;
    n_skipped = 0;

    while ( n_pass + n_skipped < 6 )
    {
        wait 1;

        if ( zmqol_any_zone_capturing() )
        {
            n_skipped++;
            continue;
        }

        maps\mp\zm_tomb_capture_zones::declare_objectives();
        n_pass++;
    }

    println( "[zm_qol] capture objectives: re-declared " + n_pass + " time(s), skipped " + n_skipped + " (capture in progress)" );
}

zmqol_any_zone_capturing()
{
    if ( !isdefined( level.zone_capture ) || !isdefined( level.zone_capture.zones ) )
        return 0;

    foreach ( zone in level.zone_capture.zones )
    {
        if ( isdefined( zone.n_objective_index ) )
            return 1;
    }

    return 0;
}

zmqol_capture_hud_nudge()
{
    level endon( "end_game" );

    if ( !is_classic() )
        return;

    for (;;)
    {
        level waittill( "connected", player );
        player thread zmqol_capture_hud_nudge_player();
    }
}

zmqol_capture_hud_nudge_player()
{
    self endon( "disconnect" );
    level endon( "end_game" );
    self waittill( "spawned_player" );
    flag_wait( "initial_blackscreen_passed" );
    b_done = 0;

    for (;;)
    {
        wait 0.25;

        if ( !zmqol_any_zone_capturing() )
        {
            b_done = 0;
            continue;
        }

        if ( b_done )
            continue;

        self setclientuivisibilityflag( "hud_visible", 0 );
        wait 0.25;
        self setclientuivisibilityflag( "hud_visible", 1 );
        b_done = 1;
        println( "[zm_qol] capture hud: nudged DURING an active capture" );
    }
}

zmqol_capture_objectives_on_connect()
{
    level endon( "end_game" );

    for (;;)
    {
        level waittill( "connected", player );
        player waittill( "spawned_player" );
        wait 0.05;

        if ( zmqol_any_zone_capturing() )
        {
            println( "[zm_qol] capture objectives: connect re-declare SKIPPED - a capture is live" );
            continue;
        }

        maps\mp\zm_tomb_capture_zones::declare_objectives();
        println( "[zm_qol] capture objectives: re-declared for a connecting player" );
    }
}

zmqol_tomb_mp40_stalker_wallbuys()
{
    level endon( "end_game" );
    n_wait = 0;

    while ( !isdefined( level._unitriggers ) || !isdefined( level._unitriggers.trigger_stubs ) || level._unitriggers.trigger_stubs.size == 0 )
    {
        wait 0.5;
        n_wait += 0.5;

        if ( n_wait > 30 )
            return 0;
    }

    wait 2;

    if ( !isdefined( level.zombie_weapons ) || !isdefined( level.zombie_weapons["mp40_stalker_zm"] ) )
    {
        println( "[zm_qol] origins mp40: mp40_stalker_zm is NOT in level.zombie_weapons - RETAG SKIPPED, wallbuys left stock" );
        return 0;
    }

    str_hint = maps\mp\zombies\_zm_weapons::get_weapon_hint( "mp40_stalker_zm" );
    n_cost = maps\mp\zombies\_zm_weapons::get_weapon_cost( "mp40_stalker_zm" );

    if ( !isdefined( str_hint ) || !isdefined( n_cost ) )
    {
        println( "[zm_qol] origins mp40: hint or cost undefined for mp40_stalker_zm - RETAG SKIPPED, wallbuys left stock" );
        return 0;
    }

    a_stubs = level._unitriggers.trigger_stubs;
    n_mp40 = 0;
    n_wb = 0;
    n_live = 0;
    a_mine = [];
    str_where = "";

    for ( i = 0; i < a_stubs.size; i++ )
    {
        if ( !isdefined( a_stubs[i] ) || !isdefined( a_stubs[i].zombie_weapon_upgrade ) )
            continue;

        n_wb++;

        if ( a_stubs[i].zombie_weapon_upgrade == "mp40_zm" || a_stubs[i].zombie_weapon_upgrade == "mp40_stalker_zm" )
        {
            if ( isdefined( a_stubs[i].origin ) )
            {
                str_where = str_where + a_stubs[i].zombie_weapon_upgrade + "(" + int( a_stubs[i].origin[0] ) + "," + int( a_stubs[i].origin[1] ) + "," + int( a_stubs[i].origin[2] ) + ") ";
            }
        }

        if ( a_stubs[i].zombie_weapon_upgrade != "mp40_zm" )
            continue;

        a_stubs[i].zombie_weapon_upgrade = "mp40_stalker_zm";

        if ( isdefined( a_stubs[i].weapon_upgrade ) )
            a_stubs[i].weapon_upgrade = "mp40_stalker_zm";

        a_stubs[i].hint_string = str_hint;
        a_stubs[i].cost = n_cost;
        n_live += a_stubs[i] zmqol_mp40_push_to_live_triggers();
        a_mine[a_mine.size] = a_stubs[i];
        n_mp40++;
    }

    if ( n_mp40 > 0 || n_live > 0 )
        println( "[zm_qol] origins mp40: retagged " + n_mp40 + " mp40 wallbuy stub(s) to mp40_stalker_zm; " + n_wb + " wallbuy stub(s) total; corrected " + n_live + " already-live trigger(s); mp40 at " + str_where );

    if ( n_mp40 == 0 && n_wb == 0 )
        level.zmqol_mp40_saw_no_stubs = 1;

    return n_mp40;
}

zmqol_mp40_keep_wallbuys_stalker()
{
    level endon( "end_game" );
    n_done = 0;
    n_passes = 0;

    while ( n_passes < 900 )
    {
        n_done += zmqol_tomb_mp40_stalker_wallbuys();
        n_passes++;

        if ( n_passes == 15 && n_done == 0 )
            println( "[zm_qol] origins mp40: STILL 0 mp40 stubs after 15 passes - wallbuy stubs are not registering at all, this is NOT the retag window" );

        wait 2;
    }
}

zmqol_mp40_push_to_live_triggers()
{
    n = 0;

    if ( isdefined( self.trigger ) )
    {
        self.trigger.zombie_weapon_upgrade = self.zombie_weapon_upgrade;

        if ( isdefined( self.trigger.weapon_upgrade ) )
            self.trigger.weapon_upgrade = self.zombie_weapon_upgrade;

        n++;
    }

    if ( isdefined( self.playertrigger ) )
    {
        keys = getarraykeys( self.playertrigger );

        for ( k = 0; k < keys.size; k++ )
        {
            if ( !isdefined( self.playertrigger[keys[k]] ) )
                continue;

            self.playertrigger[keys[k]].zombie_weapon_upgrade = self.zombie_weapon_upgrade;

            if ( isdefined( self.playertrigger[keys[k]].weapon_upgrade ) )
                self.playertrigger[keys[k]].weapon_upgrade = self.zombie_weapon_upgrade;

            n++;
        }
    }

    return n;
}

zmqol_mp40_watch_triggers( a_stubs )
{
    level endon( "end_game" );

    if ( !isdefined( a_stubs ) || a_stubs.size == 0 )
        return;

    n_ticks = 0;
    n_reported = 0;

    while ( n_ticks < 150 )
    {
        for ( i = 0; i < a_stubs.size; i++ )
        {
            if ( !isdefined( a_stubs[i] ) || !isdefined( a_stubs[i].trigger ) )
                continue;

            if ( !isdefined( a_stubs[i].trigger.zombie_weapon_upgrade ) )
                continue;

            if ( a_stubs[i].trigger.zombie_weapon_upgrade == a_stubs[i].zombie_weapon_upgrade )
                continue;

            println( "[zm_qol] origins mp40 WATCH: live trigger says " + a_stubs[i].trigger.zombie_weapon_upgrade + " but stub says " + a_stubs[i].zombie_weapon_upgrade + " - correcting" );
            a_stubs[i] zmqol_mp40_push_to_live_triggers();
            n_reported++;
        }

        wait 2;
        n_ticks++;
    }

    println( "[zm_qol] origins mp40 WATCH: done, " + n_reported + " divergence(s) seen in 5 min" );
}

zmqol_tomb_no_native_wunderfizz()
{

}

zmqol_hide_native_wunderfizz()
{
    level endon( "end_game" );
    wait 0.05;
    a_native = getentarray( "random_perk_machine", "targetname" );
    n_hidden = 0;

    for ( i = 0; i < a_native.size; i++ )
    {
        if ( !isdefined( a_native[i] ) )
            continue;

        a_native[i] setmodel( "tag_origin" );
        a_native[i] hide();
        n_hidden++;
    }

    println( "[zm_qol] origins wunderfizz: hid " + n_hidden + " of " + a_native.size + " native machine(s) - the mod's own replace them" );
}

zmqol_probe_capture_zones()
{
    if ( !is_classic() )
        return;

    flag_wait( "start_zombie_round_logic" );
    wait_network_frame();

    if ( !isdefined( level.zone_capture ) || !isdefined( level.zone_capture.zones ) )
    {
        println( "[zm_qol] capture probe: level.zone_capture MISSING - server side never initialised" );
        return;
    }

    println( "[zm_qol] capture probe: " + level.zone_capture.zones.size + " zone(s) registered" );
    a_last = [];

    for (;;)
    {
        foreach ( str_key, zone in level.zone_capture.zones )
        {
            if ( !isdefined( zone ) || !isdefined( zone.n_current_progress ) )
                continue;

            if ( isdefined( a_last[str_key] ) && a_last[str_key] == zone.n_current_progress )
                continue;

            str_obj = "unset";

            if ( isdefined( zone.n_objective_index ) )
                str_obj = "" + zone.n_objective_index;

            println( "[zm_qol] capture probe: zone " + str_key + " progress " + zone.n_current_progress + " obj=" + str_obj + " contested=" + zone ent_flag( "zone_contested" ) + " player_controlled=" + zone ent_flag( "player_controlled" ) + " inzone=" + zone maps\mp\zm_tomb_capture_zones::get_players_in_capture_zone().size );
            a_last[str_key] = zone.n_current_progress;
        }

        wait 0.5;
    }
}

zmqol_power_up_all_generators()
{
    if ( is_classic() )
        return;

    flag_wait( "start_zombie_round_logic" );
    wait_network_frame();

    if ( !isdefined( level.zone_capture ) || !isdefined( level.zone_capture.zones ) )
        return;

    foreach ( zone in level.zone_capture.zones )
    {
        zone maps\mp\zm_tomb_capture_zones::set_player_controlled_area();
        zone.n_current_progress = 100;
        zone maps\mp\zm_tomb_capture_zones::generator_state_power_up();
        level setclientfield( zone.script_noteworthy, zone.n_current_progress / 100 );
        wait_network_frame();
    }
}

zmqol_disable_staff_relay_switches()
{
    if ( is_classic() )
        return;

    flag_wait( "start_zombie_round_logic" );
    wait_network_frame();

    if ( !isdefined( level.electric_relays ) )
        return;

    foreach ( s_relay in level.electric_relays )
    {
        if ( isdefined( s_relay.trigger_stub ) )
            maps\mp\zombies\_zm_unitrigger::unregister_unitrigger( s_relay.trigger_stub );
    }
}

zmqol_remove_survival_ee_props()
{
    if ( is_classic() )
        return;

    n_waited = 0;

    while ( !isdefined( level.vh_tank ) && n_waited < 200 )
    {
        n_waited++;
        wait 0.05;
    }

    a_call_boxes = getentarray( "trig_tank_station_call", "targetname" );

    foreach ( trigger in a_call_boxes )
    {
        if ( isdefined( trigger ) )
            trigger delete();
    }

    t_use_tank = getent( "trig_use_tank", "targetname" );

    if ( isdefined( t_use_tank ) )
        t_use_tank delete();

    e_tank = getent( "tank", "targetname" );

    if ( isdefined( e_tank ) )
        e_tank delete();

    level.vh_tank = undefined;
    a_boxes = getentarray( "foot_box", "script_noteworthy" );

    foreach ( box in a_boxes )
    {
        if ( isdefined( box ) )
            box delete();
    }
}

zmqol_open_stock_barriers()
{
    if ( is_classic() )
        return;

    flag_wait( "start_zombie_round_logic" );
    wait_network_frame();
    a_goals = getstructarray( "exterior_goal", "targetname" );
    n_opened = 0;

    foreach ( s_goal in a_goals )
    {
        if ( !isdefined( s_goal.target ) )
            continue;

        a_targets = getentarray( s_goal.target, "targetname" );

        foreach ( e_barrier in a_targets )
        {
            if ( !isdefined( e_barrier ) || !e_barrier iszbarrier() )
                continue;

            n_pieces = e_barrier getnumzbarrierpieces();

            for ( i = 0; i < n_pieces; i++ )
            {
                e_barrier hidezbarrierpiece( i );
                e_barrier setzbarrierpiecestate( i, "open" );
            }

            n_opened++;
            wait 0.05;
        }
    }

    println( "[zm_qol] BARRIERS opened " + n_opened + " stock zbarriers" );
}

added_weapons()
{
    if ( level.script == "zm_tomb" )
    {
        include_weapon( "uzi_zm" );
        include_weapon( "uzi_upgraded_zm", 0 );
        add_zombie_weapon( "uzi_zm", "uzi_upgraded_zm", &"ZOMBIE_WEAPON_UZI", 1500, "wpck_smg", "", undefined );
        include_weapon( "ak47_zm" );
        include_weapon( "ak47_upgraded_zm", 0 );
        add_zombie_weapon( "ak47_zm", "ak47_upgraded_zm", &"ZOMBIE_WEAPON_AK47", 500, "wpck_mg", "", undefined, 1 );
        include_weapon( "minigun_alcatraz_zm" );
        include_weapon( "minigun_alcatraz_upgraded_zm", 0 );
        add_zombie_weapon( "minigun_alcatraz_zm", "minigun_alcatraz_upgraded_zm", &"ZOMBIE_WEAPON_RPD", 50, "wpck_mg", "", undefined, 1 );
        include_weapon( "hk416_zm" );
        include_weapon( "hk416_upgraded_zm", 0 );
        add_zombie_weapon( "hk416_zm", "hk416_upgraded_zm", &"ZOMBIE_WEAPON_HK416", 100, "", "", undefined );
        include_weapon( "rnma_zm" );
        include_weapon( "rnma_upgraded_zm", 0 );
        add_zombie_weapon( "rnma_zm", "rnma_upgraded_zm", &"ZOMBIE_WEAPON_RNMA", 50, "pickup_six_shooter", "", undefined, 1 );
        include_weapon( "an94_zm" );
        include_weapon( "an94_upgraded_zm", 0 );
        add_zombie_weapon( "an94_zm", "an94_upgraded_zm", &"ZOMBIE_WEAPON_AN94", 1200, "", "", undefined );
        include_weapon( "lsat_zm" );
        include_weapon( "lsat_upgraded_zm", 0 );
        add_zombie_weapon( "lsat_zm", "lsat_upgraded_zm", &"ZOMBIE_WEAPON_LSAT", 2000, "wpck_lsat", "", undefined, 1 );
        include_weapon( "svu_zm" );
        include_weapon( "svu_upgraded_zm", 0 );
        add_zombie_weapon( "svu_zm", "svu_upgraded_zm", &"ZOMBIE_WEAPON_SVU", 1000, "wpck_svuas", "", undefined );
        include_weapon( "xm8_zm" );
        include_weapon( "xm8_upgraded_zm", 0 );
        add_zombie_weapon( "xm8_zm", "xm8_upgraded_zm", &"ZOMBIE_WEAPON_XM8", 50, "wpck_m8a1", "", undefined, 1 );
        include_weapon( "rpd_zm" );
        include_weapon( "rpd_upgraded_zm", 0 );
        add_zombie_weapon( "rpd_zm", "rpd_upgraded_zm", &"ZOMBIE_WEAPON_RPD", 50, "wpck_rpd", "", undefined, 1 );
        include_weapon( "saritch_zm" );
        include_weapon( "saritch_upgraded_zm", 0 );
        add_zombie_weapon( "saritch_zm", "saritch_upgraded_zm", &"ZOMBIE_WEAPON_SARITCH", 50, "wpck_sidr", "", undefined, 1 );
        include_weapon( "m16_zm" );
        include_weapon( "m16_gl_upgraded_zm", 0 );
        add_zombie_weapon( "m16_zm", "m16_gl_upgraded_zm", &"ZOMBIE_WEAPON_M16", 1200, "burstrifle", "", undefined );
        include_weapon( "barretm82_zm" );
        include_weapon( "barretm82_upgraded_zm", 0 );
        add_zombie_weapon( "barretm82_zm", "barretm82_upgraded_zm", &"ZOMBIE_WEAPON_BARRETM82", 50, "sniper", "", undefined );
        include_weapon( "mp5k_zm" );
        include_weapon( "mp5k_upgraded_zm", 0 );
        add_zombie_weapon( "mp5k_zm", "mp5k_upgraded_zm", &"ZOMBIE_WEAPON_MP5K", 1000, "smg", "", undefined );
        include_weapon( "tar21_zm" );
        include_weapon( "tar21_upgraded_zm", 0 );
        add_zombie_weapon( "tar21_zm", "tar21_upgraded_zm", &"ZOMBIE_WEAPON_TAR21", 50, "wpck_x95l", "", undefined, 1 );
        include_weapon( "rottweil72_zm" );
        include_weapon( "rottweil72_upgraded_zm", 0 );
        add_zombie_weapon( "rottweil72_zm", "rottweil72_upgraded_zm", &"ZOMBIE_WEAPON_ROTTWEIL72", 500, "shotgun", "", undefined );
        include_weapon( "saiga12_zm" );
        include_weapon( "saiga12_upgraded_zm", 0 );
        add_zombie_weapon( "saiga12_zm", "saiga12_upgraded_zm", &"ZOMBIE_WEAPON_SAIGA12", 50, "wpck_saiga12", "", undefined, 1 );
        include_weapon( "m1911_zm" );
        include_weapon( "m1911_upgraded_zm", 0 );
        add_zombie_weapon( "m1911_zm", "m1911_upgraded_zm", &"ZOMBIE_WEAPON_M1911", 50, "", "", undefined );
        include_weapon( "judge_zm" );
        include_weapon( "judge_upgraded_zm", 0 );
        add_zombie_weapon( "judge_zm", "judge_upgraded_zm", &"ZOMBIE_WEAPON_JUDGE", 50, "wpck_judge", "", undefined, 1 );
        include_weapon( "usrpg_zm" );
        include_weapon( "usrpg_upgraded_zm", 0 );
        add_zombie_weapon( "usrpg_zm", "usrpg_upgraded_zm", &"ZOMBIE_WEAPON_USRPG", 50, "wpck_rpg", "", undefined, 1 );
    }
}

custom_swap_weapon( str_weapon, e_player )
{
    if ( isdefined( level.zombie_weapons[str_weapon] ) && isdefined( level.zombie_weapons[str_weapon].upgrade_name ) )
    {
        upgraded_weapon = level.zombie_weapons[str_weapon].upgrade_name;

        if ( e_player hasweapon( upgraded_weapon ) )
        {
            e_player givemaxammo( upgraded_weapon );
            return;
        }
    }

    str_current_weapon = e_player getcurrentweapon();

    if ( str_weapon == "claymore_zm" )
    {
        if ( !e_player hasweapon( str_weapon ) )
        {
            e_player thread maps\mp\zombies\_zm_weap_claymore::show_claymore_hint( "claymore_purchased" );
            e_player thread maps\mp\zombies\_zm_weap_claymore::claymore_setup();
            e_player thread maps\mp\zombies\_zm_audio::create_and_play_dialog( "weapon_pickup", "grenade" );
        }
        else
        {
            e_player givemaxammo( str_weapon );
        }

        return;
    }

    if ( is_player_valid( e_player ) && !e_player.is_drinking && !is_placeable_mine( str_current_weapon ) && !is_equipment( str_current_weapon ) && level.revive_tool != str_current_weapon && str_current_weapon != "none" && !e_player hacker_active() )
    {
        if ( !e_player hasweapon( str_weapon ) )
        {
            e_player maps\mp\zm_tomb_dig::take_old_weapon_and_give_new( str_current_weapon, str_weapon );
            return;
        }
        else
        {
            e_player givemaxammo( str_weapon );
        }
    }
}

origins_change_patch()
{
    while ( true )
    {
        self waittill( "trigger", e_player );

        if ( e_player getstance() == "prone" )
        {
            e_player maps\mp\zombies\_zm_score::add_to_player_score( 100 );
            play_sound_at_pos( "purchase", e_player.origin );
            break;
        }

        wait 0.1;
    }
}

qol_check_solo_status()
{
    n_expected = getnumexpectedplayers();

    if ( n_expected <= 1 )
        level.is_forever_solo_game = 1;
    else
        level.is_forever_solo_game = 0;

    println( "[zm_qol] solo status: expected=" + n_expected + " connected=" + getnumconnectedplayers() + " is_forever_solo_game=" + level.is_forever_solo_game );
}
