#!/usr/bin/env python3
"""
gen_index.py - generate CODE_INDEX.md, a name -> file:line map for zm_qol.

DRAFTED BY THE ARENA AGENT. The generator is verified in the Arena sandbox
(see the self-check at the bottom of its output); the INDEX IT PRODUCES is
mechanical fact - every entry is a line number you can open.

WHY THIS EXISTS
    scripts/zm/quality_of_life.gsc is 15,743 lines. CLAUDE.md describes it as
    "~3500 lines" and MOD_CATALOGUE section 1a says 7,264. Both are wrong, so
    every session budgets a read of that file at a fraction of its real cost.
    Reading it to find one function is the single most expensive habit in this
    project, and it is paid out of a metered Pro window.

    With this index a session greps CODE_INDEX.md (a few KB) and then reads a
    50-line window at a known offset instead of slurping 15,743 lines.

WHAT IT INDEXES
    - every function definition in every .gsc / .csc, with its line
    - which functions are replaceFunc'd over stock, and where
    - which dvars each file reads, and where they are registered
    - the module banner comments inside quality_of_life.gsc, so the 17 merged
      modules can be navigated

USAGE
    python gen_index.py                 # writes handoff/CODE_INDEX.md
    python gen_index.py --stdout        # print instead of writing
"""

import argparse
import os
import re
import sys

# A GSC function definition is a name at column 0 followed by ( ... ) and a
# brace on the next line. Verified against quality_of_life.gsc: 273 matches,
# and its known functions (main at 85, init at 507) land correctly.
FUNC_RE = re.compile(r'^([a-zA-Z_][a-zA-Z_0-9]*)\s*\(([^)]*)\)\s*$', re.MULTILINE)

# 🛑 The replacement half has TWO shapes and an early version of this regex
# only matched the first, silently missing two real hooks:
#     replaceFunc( stock::fn, ::local_fn )                        - 40 of them
#     replaceFunc( stock::fn, scripts\zm\replaced\utility::fn )   - 2 of them
# The two missed were quality_of_life.gsc:168 (struct_class_init) and
# zm_transit.gsc:26 (zm_transit_gamemodes::init) - both load-bearing. An index
# that quietly omits a hook is worse than no index, so the second alternative
# is explicit here.
REPLACEFUNC_RE = re.compile(
    r'replaceFunc\s*\(\s*([^,]+?)\s*,\s*'
    r'(::[a-zA-Z_][a-zA-Z_0-9]*|[A-Za-z_][A-Za-z_0-9\\]*::[a-zA-Z_][a-zA-Z_0-9]*)\s*\)',
    re.IGNORECASE)

QOL_OPT_RE = re.compile(r'qol_opt_dvar\s*\(\s*"([A-Za-z_0-9]+)"\s*,\s*"([^"]*)"')
GETDVAR_RE = re.compile(r'getdvar(?:int|float)?default?\s*\(\s*"([A-Za-z_0-9]+)"', re.IGNORECASE)

# A banner is a ==== rule followed by a //  Title line.
BANNER_RE = re.compile(r'^//\s{2,}([A-Za-z0-9][^\n]{3,70})$', re.MULTILINE)


def strip_comments(src):
    """Same routine as preflight.py. Line numbers are preserved."""
    out = []
    i, n = 0, len(src)
    line_c = block_c = in_str = False
    while i < n:
        c = src[i]
        nxt = src[i + 1] if i + 1 < n else ''
        if line_c:
            if c == '\n':
                line_c = False
                out.append(c)
            else:
                out.append(' ')
        elif block_c:
            if c == '*' and nxt == '/':
                block_c = False
                out.append('  ')
                i += 2
                continue
            out.append('\n' if c == '\n' else ' ')
        elif in_str:
            out.append(c)
            if c == '\\':
                if i + 1 < n:
                    out.append(nxt)
                    i += 2
                    continue
            elif c == '"':
                in_str = False
        else:
            if c == '/' and nxt == '/':
                line_c = True
                out.append('  ')
                i += 2
                continue
            if c == '/' and nxt == '*':
                block_c = True
                out.append('  ')
                i += 2
                continue
            if c == '"':
                in_str = True
            out.append(c)
        i += 1
    return ''.join(out)


def line_of(text, idx):
    return text.count('\n', 0, idx) + 1


def scripts_in(root):
    out = []
    for base, dirs, files in os.walk(root):
        parts = base.split(os.sep)
        if '.git' in parts or 'zone_assets' in parts:
            continue
        for f in sorted(files):
            if f.endswith(('.gsc', '.csc')):
                out.append(os.path.join(base, f))
    return sorted(out)


def build(root):
    lines = []
    add = lines.append

    add('# CODE_INDEX.md — generated navigation map for zm_qol')
    add('')
    add('**Generated by `handoff/gen_index.py`. Do not hand-edit — regenerate it.**')
    add('')
    add('Every entry is `file:line`. Open a window at the offset instead of reading the')
    add('whole file. `quality_of_life.gsc` alone is 15,743 lines; reading it to find one')
    add('function is the most expensive habit in this project and it is paid out of a')
    add('metered Pro window.')
    add('')
    add('Regenerate after any change that moves functions:')
    add('')
    add('```')
    add('python handoff\\gen_index.py')
    add('```')
    add('')

    files = scripts_in(root)

    # ---- size table, so the real cost of a read is never a guess -------
    add('## File sizes — measured, not from the docs')
    add('')
    add('🛑 `CLAUDE.md` calls `quality_of_life.gsc` "~3500 lines" and `MOD_CATALOGUE.md`')
    add('§1a says 7,264. Both are stale. These are `wc -l` at generation time.')
    add('')
    add('| file | lines |')
    add('|---|---:|')
    total = 0
    sizes = []
    for path in files:
        with open(path, 'rb') as fh:
            n = fh.read().count(b'\n')
        total += n
        sizes.append((n, os.path.relpath(path, root).replace(os.sep, '/')))
    for n, rel in sorted(sizes, reverse=True):
        if n >= 100:
            add(f'| `{rel}` | {n:,} |')
    add(f'| **total, {len(files)} files** | **{total:,}** |')
    add('')

    # ---- replaceFunc inventory ----------------------------------------
    add('## replaceFunc inventory — what this mod overrides in stock')
    add('')
    add('🛑 `replaceFunc` fails silently in four known ways, and has been measured NOT')
    add('taking on `_zm_perks::give_perk`. Presence in this table means the call exists,')
    add('**not** that the hook fires. Prove it with a print before building on it.')
    add('')
    add('| stock function replaced | with | where |')
    add('|---|---|---|')
    rf_rows = []
    for path in files:
        src = strip_comments(open(path, encoding='utf-8', errors='replace').read())
        rel = os.path.relpath(path, root).replace(os.sep, '/')
        for m in REPLACEFUNC_RE.finditer(src):
            target = ' '.join(m.group(1).split())
            rf_rows.append((target, m.group(2), f'{rel}:{line_of(src, m.start())}'))
    for target, repl, where in sorted(rf_rows):
        add(f'| `{target}` | `{repl}` | {where} |')
    add('')
    add(f'*{len(rf_rows)} replaceFunc call(s).*')
    add('')

    # ---- dvar registry -------------------------------------------------
    add('## Dvar registry')
    add('')
    add('Registered = created by `qol_opt_dvar`, so it exists at the console.')
    add('**Unregistered** = read with `getdvar*default()`, which returns the default')
    add('*without creating the dvar*, so typing it at the console is an unknown command.')
    add('See finding H-002 in `HANDOFF.md`.')
    add('')
    registered = {}
    reads = {}
    for path in files:
        src = strip_comments(open(path, encoding='utf-8', errors='replace').read())
        rel = os.path.relpath(path, root).replace(os.sep, '/')
        for m in QOL_OPT_RE.finditer(src):
            registered[m.group(1)] = (m.group(2), f'{rel}:{line_of(src, m.start())}')
        for m in GETDVAR_RE.finditer(src):
            reads.setdefault(m.group(1), []).append(f'{rel}:{line_of(src, m.start())}')

    add('### Registered')
    add('')
    add('| dvar | default | registered at |')
    add('|---|---|---|')
    for name in sorted(registered):
        default, where = registered[name]
        add(f'| `{name}` | `{default}` | {where} |')
    add('')

    unreg = sorted(n for n in reads if n not in registered)
    add(f'### Read but never registered ({len(unreg)})')
    add('')
    add('| dvar | first read at | reads |')
    add('|---|---|---:|')
    for name in unreg:
        add(f'| `{name}` | {reads[name][0]} | {len(reads[name])} |')
    add('')

    # ---- function index ------------------------------------------------
    add('## Function index')
    add('')
    add('Alphabetical within each file.')
    add('')
    grand = 0
    for path in files:
        raw = open(path, encoding='utf-8', errors='replace').read()
        src = strip_comments(raw)
        rel = os.path.relpath(path, root).replace(os.sep, '/')
        funcs = [(m.group(1), line_of(src, m.start()))
                 for m in FUNC_RE.finditer(src)]
        if not funcs:
            continue
        grand += len(funcs)
        add(f'### `{rel}` — {len(funcs)} function(s)')
        add('')
        for name, ln in sorted(funcs):
            add(f'- `{name}()` — {rel}:{ln}')
        add('')

    add(f'*{grand} function definitions indexed across {len(files)} files.*')
    add('')

    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default=None)
    ap.add_argument('--stdout', action='store_true')
    args = ap.parse_args()
    root = args.root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if not os.path.isdir(os.path.join(root, 'scripts')):
        print(f'ERROR: {root} is not the zm_qol repo')
        return 2
    text = build(root)
    if args.stdout:
        sys.stdout.write(text)
    else:
        # Written into handoff/, not the repo root. The root of this repo is
        # what mod downloaders see; an AI navigation map does not belong there.
        out = os.path.join(root, 'handoff', 'CODE_INDEX.md')
        with open(out, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(text)
        print(f'wrote {out} ({len(text):,} bytes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
